export const MaleData = {
    getMaleData : function() {
        return [
            {
              "Id": 1,
              "Player_Name": "Rushabh Kishor Nagda",
              "Mobile_Number": 8097598191,
              "Location": "Borivali",
              "Village": "Bhinsara",
              "NPL1_NPL2": "Both",
              "Cricket_Type": "Batting",
              "TShirt_Size": "M",
              "Age": 27,
              "Gender": "Male",
              "Payment_SS": "https://drive.google.com/open?id=1ZKIPELe4QzLasjTrY1udSK9fK5lYYVAW",
              "Photo": "https://drive.google.com/open?id=14sHjV4Kl4VcNJxjMdHd_DqissEFK98dK",
              "Email_Id": "rushabh1114@gmail.com",
              "Status": "Not Sold"
            },
            {
              "Id": 2,
              "Player_Name": "Smit Praful Nagda",
              "Mobile_Number": 8554034221,
              "Location": "Vasai",
              "Village": "Sanosara",
              "NPL1_NPL2": "NPL-2",
              "Cricket_Type": "Allrounder",
              "TShirt_Size": "XL",
              "Age": 24,
              "Gender": "Male",
              "Payment_SS": "https://drive.google.com/open?id=1jlKzUxtV_ck_F0Hib_Rii-KmX40K7m1U",
              "Photo": "https://drive.google.com/open?id=1xeS7NJZDSEZuZOHNvbcs6edf8SYAFUbZ",
              "Email_Id": "Smitnagda8554034221@gmail.com",
              "Status": "Not Sold"
            },
            {
              "Id": 3,
              "Player_Name": "HARSH AMISH NAGDA",
              "Mobile_Number": 9967067021,
              "Location": "Mulund",
              "Village": "Sabharai",
              "NPL1_NPL2": "Both",
              "Cricket_Type": "Allrounder",
              "TShirt_Size": "Xxl",
              "Age": 31,
              "Gender": "Male",
              "Payment_SS": "https://drive.google.com/open?id=1HqWhVPq0qkbWXybqVkhqfEFzl5BttG15",
              "Photo": "https://drive.google.com/open?id=1I3QldqJ4Xo9AnRVNNuPMOzHL5bRVsB3v",
              "Email_Id": "harshnagda@yahoo.com",
              "Status": "Not Sold"
            },
            {
              "Id": 4,
              "Player_Name": "Palak Nagda",
              "Mobile_Number": 9969310500,
              "Location": "Kandivali",
              "Village": "Bhojay",
              "NPL1_NPL2": "None",
              "Cricket_Type": "Allrounder",
              "TShirt_Size": "XL",
              "Age": 23,
              "Gender": "Male",
              "Payment_SS": "https://drive.google.com/open?id=1XZJisZbmNFRnuS-F2Ssv5tUIMaqg_bgZ",
              "Photo": "https://drive.google.com/open?id=1RuuLQEnVGnDqkZ8f3pxRs3BU5cLBsyv8",
              "Email_Id": "thepalaknagda@gmail.com",
              "Status": "Not Sold"
            },
            {
              "Id": 5,
              "Player_Name": "Rahul Devchand Nagda",
              "Mobile_Number": 9022720865,
              "Location": "Malad",
              "Village": "Vindh",
              "NPL1_NPL2": "None",
              "Cricket_Type": "Allrounder",
              "TShirt_Size": "M",
              "Age": 30,
              "Gender": "Male",
              "Payment_SS": "https://drive.google.com/open?id=1lhGMsiZj5SZ9As_9HLDIdzw8a8WXxm7W",
              "Photo": "https://drive.google.com/open?id=1HABF_rpyfUWdXwcZ4Rnt7oESzCEw4s2I",
              "Email_Id": "nagda.rahul27@gmail.com",
              "Status": "Not Sold"
            },
            {
              "Id": 6,
              "Player_Name": "Amit Suresh nagda",
              "Mobile_Number": 9892931665,
              "Location": "Dahisar",
              "Village": "Bhojay",
              "NPL1_NPL2": "None",
              "Cricket_Type": "Allrounder",
              "TShirt_Size": "XL",
              "Age": 41,
              "Gender": "Male",
              "Payment_SS": "https://drive.google.com/open?id=1TaI-StT9Fm8Ihgg8igjvtAxWWJIYuRkF",
              "Photo": "https://drive.google.com/open?id=1QSAdIUBbibCDuBHd0q6CIllJzUuFWgAe",
              "Email_Id": "amitnagda99@yahoo.com",
              "Status": "Not Sold"
            },
            {
              "Id": 7,
              "Player_Name": "Jatin dilip nagda",
              "Mobile_Number": 9930651508,
              "Location": "Dombivli",
              "Village": "Karagoga",
              "NPL1_NPL2": "Both",
              "Cricket_Type": "Allrounder",
              "TShirt_Size": "Xl",
              "Age": 33,
              "Gender": "Male",
              "Payment_SS": "https://drive.google.com/open?id=1AefZbMUxgaFDQKhck56MqXSdzsAAFbeB",
              "Photo": "https://drive.google.com/open?id=1z-6HmzfJEJBbXmULF444joA1UleXeRjT",
              "Email_Id": "Jatinnagada0104@gmail.com",
              "Status": "Not Sold"
            },
            {
              "Id": 8,
              "Player_Name": "Viken shamji nagda",
              "Mobile_Number": 9326337234,
              "Location": "Dombivali",
              "Village": "Vidha",
              "NPL1_NPL2": "Both",
              "Cricket_Type": "Bowling",
              "TShirt_Size": "Xxl",
              "Age": 33,
              "Gender": "Male",
              "Payment_SS": "https://drive.google.com/open?id=1kexY2jeV-Mstl8_tEWfts2qzpxtV7BGq",
              "Photo": "https://drive.google.com/open?id=18s3JsVXInU0cMVFnxfPdOiWX12YcY349",
              "Email_Id": "Nagdaviken@gamil.com",
              "Status": "Not Sold"
            },
            {
              "Id": 9,
              "Player_Name": "Sanyam Gautam Shah/Nagda",
              "Mobile_Number": 7020890757,
              "Location": "Virar",
              "Village": "Naredi",
              "NPL1_NPL2": "NPL-2",
              "Cricket_Type": "Allrounder",
              "TShirt_Size": "L",
              "Age": 20,
              "Gender": "Male",
              "Payment_SS": "https://drive.google.com/open?id=1NGEXynG-1eu3MAFAClJpa3BNOGUHRkZa",
              "Photo": "https://drive.google.com/open?id=1D-AqmnCK1nfhC5VUNQGiQBOBzLeneg8e",
              "Email_Id": "Sanyamshah2305@gmail.com",
              "Status": "Not Sold"
            },
            {
              "Id": 10,
              "Player_Name": "Hardik Kishor Nagda",
              "Mobile_Number": 7709181594,
              "Location": "Mumbai",
              "Village": "Sanosara",
              "NPL1_NPL2": "NPL-1",
              "Cricket_Type": "Allrounder",
              "TShirt_Size": "M",
              "Age": 33,
              "Gender": "Male",
              "Payment_SS": "https://drive.google.com/open?id=1Svamr7kj5k8ZplrEvzacWQLrYMhXCCxu",
              "Photo": "https://drive.google.com/open?id=1fuFp9K0D4B3uw_miytPiGG2PacLPPu8k",
              "Email_Id": "Nagada.hardik@gmail.com",
              "Status": "Not Sold"
            },
            {
              "Id": 11,
              "Player_Name": "Chirag damji nagda",
              "Mobile_Number": 9821392929,
              "Location": "Mulund east",
              "Village": "Naredi",
              "NPL1_NPL2": "NPL-2",
              "Cricket_Type": "Batting",
              "TShirt_Size": "Xl",
              "Age": 38,
              "Gender": "Male",
              "Payment_SS": "https://drive.google.com/open?id=1RMYyYx8UUPqvfo5kcELIioGfy0139074",
              "Photo": "https://drive.google.com/open?id=1oOF70w55CgbL7TaIKENqpYgrE1E5kmfv",
              "Email_Id": "chiragnagda.0910@gmail.com",
              "Status": "Not Sold"
            },
            {
              "Id": 12,
              "Player_Name": "Chirag Rakesh Shah / Nagda",
              "Mobile_Number": 7738837875,
              "Location": "Kalyan",
              "Village": "Vidh",
              "NPL1_NPL2": "NPL-2",
              "Cricket_Type": "Allrounder",
              "TShirt_Size": "XL",
              "Age": 20,
              "Gender": "Male",
              "Payment_SS": "https://drive.google.com/open?id=1k4GOPCFJpjA_bZyAQw00y5B3iTO8fjES",
              "Photo": "https://drive.google.com/open?id=12rbz_pFgFzboUcL8MzWkra5ky2bNW2tD",
              "Email_Id": "nschirag2003@gmail.com",
              "Status": "Not Sold"
            },
            {
              "Id": 13,
              "Player_Name": "Gautam Raichand Shah/Nagda",
              "Mobile_Number": 9322111190,
              "Location": "Virar",
              "Village": "Naredi",
              "NPL1_NPL2": "NPL-2",
              "Cricket_Type": "Allrounder",
              "TShirt_Size": "XXL",
              "Age": 52,
              "Gender": "Male",
              "Payment_SS": "https://drive.google.com/open?id=1GlY94sEaKgRQYzwUytmrIqU8rQZEe9PB",
              "Photo": "https://drive.google.com/open?id=1o6hpaxvpHRkp-yWw_H7Fjsbky_eyLHvw",
              "Email_Id": "gautamshah1970@gmail.com",
              "Status": "Not Sold"
            },
            {
              "Id": 14,
              "Player_Name": "Akshit Rajesh nagda",
              "Mobile_Number": 8956795831,
              "Location": "Ambernath",
              "Village": "Kotdi Mahadev puri",
              "NPL1_NPL2": "NPL-2",
              "Cricket_Type": "Allrounder",
              "TShirt_Size": "Xxl",
              "Age": 21,
              "Gender": "Male",
              "Payment_SS": "https://drive.google.com/open?id=1zFdFaU_wewd1lUiqn27j34IPxG6c8kSV",
              "Photo": "https://drive.google.com/open?id=1AmZJYihHXMsaw_mXGgAfTVWO2IFErPkb",
              "Email_Id": "nagdakingaki31@gmail.com",
              "Status": "Not Sold"
            },
            {
              "Id": 15,
              "Player_Name": "JIGAR PRAKASH SHAH/NAGDA",
              "Mobile_Number": 9022645274,
              "Location": "Byculla",
              "Village": "Bhisra",
              "NPL1_NPL2": "NPL-1",
              "Cricket_Type": "Allrounder",
              "TShirt_Size": "5XL",
              "Age": 30,
              "Gender": "Male",
              "Payment_SS": "https://drive.google.com/open?id=1_pPRmFQDv6aLwktRhQJ8OeZpxtm3Zy25",
              "Photo": "https://drive.google.com/open?id=1EzVAPB-n_OxYhDEGCbAQ2e4TVXSJSxh3",
              "Email_Id": "jiasdesign123@gmail.com",
              "Status": "Not Sold"
            },
            {
              "Id": 16,
              "Player_Name": "Kalpesh Damji Nagda",
              "Mobile_Number": 9819706426,
              "Location": "Thana",
              "Village": "Sanosara",
              "NPL1_NPL2": "Both",
              "Cricket_Type": "Allrounder",
              "TShirt_Size": "M",
              "Age": 45,
              "Gender": "Male",
              "Payment_SS": "https://drive.google.com/open?id=1vvH5QP1nwVLYcaip4q5Az-vNBIj5kwpw",
              "Photo": "https://drive.google.com/open?id=1sw2N5eJuSytg21gNubUE7sSX_Y5jWUuP",
              "Email_Id": "kalpz30@gmail.com",
              "Status": "Not Sold"
            },
            {
              "Id": 17,
              "Player_Name": "Chunmay Gautam Shah/Nagda",
              "Mobile_Number": 9307388951,
              "Location": "Virar",
              "Village": "Naredi",
              "NPL1_NPL2": "NPL-2",
              "Cricket_Type": "Allrounder",
              "TShirt_Size": "L",
              "Age": 17,
              "Gender": "Male",
              "Payment_SS": "https://drive.google.com/open?id=1EdpVIxngnYuu09HjQRCXvHi7uGEGqjxF",
              "Photo": "https://drive.google.com/open?id=1EzcGtTZQHkuOlXHe69UBG9EM1BYXwieZ",
              "Email_Id": "shahchunmay@gmail.com",
              "Status": "Not Sold"
            },
            {
              "Id": 18,
              "Player_Name": "Rajesh gosar nagda",
              "Mobile_Number": 9730659901,
              "Location": "Ambernath",
              "Village": "Kotdi mahadev puri",
              "NPL1_NPL2": "Both",
              "Cricket_Type": "Allrounder",
              "TShirt_Size": "Xl",
              "Age": 53,
              "Gender": "Male",
              "Payment_SS": "https://drive.google.com/open?id=1afpBOO78F_y9J8xyxZgJSsZOcPKyzdbK",
              "Photo": "https://drive.google.com/open?id=1hD3JAvLZbkk4F3RkeN4JK0Fc0Pt-yM6a",
              "Email_Id": "nagdarajesh271267@gmail.com",
              "Status": "Not Sold"
            },
            {
              "Id": 19,
              "Player_Name": "Prakash Kalyanji Shah/Nagda",
              "Mobile_Number": 9820987030,
              "Location": "Byculla",
              "Village": "Bhisra",
              "NPL1_NPL2": "NPL-1",
              "Cricket_Type": "Allrounder",
              "TShirt_Size": "XXL",
              "Age": 52,
              "Gender": "Male",
              "Payment_SS": "https://drive.google.com/open?id=1cyf_TZK1ub0uPk13l0M89fhSAspO67oa",
              "Photo": "https://drive.google.com/open?id=1AqzgoQ8whXx3Teb1jfdPE4LmeJP6cj16",
              "Email_Id": "nehavora12@gmail.com",
              "Status": "Not Sold"
            },
            {
              "Id": 20,
              "Player_Name": "Amish Rasiklal Nagda",
              "Mobile_Number": 9323948694,
              "Location": "Mulund",
              "Village": "Sabrai",
              "NPL1_NPL2": "Both",
              "Cricket_Type": "Allrounder",
              "TShirt_Size": "XL",
              "Age": 58,
              "Gender": "Male",
              "Payment_SS": "https://drive.google.com/open?id=125GsFDK8gw57CkdkTxoi0CTIjYIou26N",
              "Photo": "https://drive.google.com/open?id=1pgzFmCjmLDEJGxKJiRU1bbvqqp4MutHT",
              "Email_Id": "awanidedhia@gmail.com",
              "Status": "Not Sold"
            },
            {
              "Id": 21,
              "Player_Name": "Ritesh nagda",
              "Mobile_Number": 9892369907,
              "Location": "Bhayander",
              "Village": "Naredi",
              "NPL1_NPL2": "Both",
              "Cricket_Type": "Allrounder",
              "TShirt_Size": "L",
              "Age": 37,
              "Gender": "Male",
              "Payment_SS": "https://drive.google.com/open?id=1lFcfz5wuxQmZG_Z36LVJM3issC22r-to",
              "Photo": "https://drive.google.com/open?id=1LM_KczrPt0-bALkcFdNR99Cjp8UlqGwZ",
              "Email_Id": "riteshnagda84@gmail.com",
              "Status": "Not Sold"
            },
            {
              "Id": 22,
              "Player_Name": "Mahesh Damji Shah",
              "Mobile_Number": 9867431637,
              "Location": "Bhandup West",
              "Village": "Sanosara",
              "NPL1_NPL2": "NPL-2",
              "Cricket_Type": "Allrounder",
              "TShirt_Size": "M",
              "Age": 46,
              "Gender": "Male",
              "Payment_SS": "https://drive.google.com/open?id=1LnRAE5HtsgKcQUxNnMmQX0q_bkspr0Qm",
              "Photo": "https://drive.google.com/open?id=1SuHVj3TlCRLiTxpQqH8PrbZS8hE0CjCR",
              "Email_Id": "mahesh021277@gail.com",
              "Status": "Not Sold"
            },
            {
              "Id": 23,
              "Player_Name": "Mihir Jayantilal Nagda",
              "Mobile_Number": 9664875667,
              "Location": "Virar west",
              "Village": "Sanosara",
              "NPL1_NPL2": "None",
              "Cricket_Type": "Bowling",
              "TShirt_Size": "XXXL",
              "Age": 32,
              "Gender": "Male",
              "Payment_SS": "https://drive.google.com/open?id=1CN9Y50M_yfLPLxahENkVpVbGjNJrPyTq",
              "Photo": "https://drive.google.com/open?id=1_Z-ei6jaz-51mGmatknhrbK3CCJZhRiW",
              "Email_Id": "mihirrockes99@gmail.com",
              "Status": "Not Sold"
            },
            {
              "Id": 24,
              "Player_Name": "Ramesh Nagda",
              "Mobile_Number": 8108051007,
              "Location": "Mulund",
              "Village": "Naredi",
              "NPL1_NPL2": "Both",
              "Cricket_Type": "Bowling",
              "TShirt_Size": "XL",
              "Age": 46,
              "Gender": "Male",
              "Payment_SS": "https://drive.google.com/open?id=1_fGA_B38MT_-UcvDO3suXtXZNF4fkYPW",
              "Photo": "https://drive.google.com/open?id=11gM6vtsbFPRkqX2zEL1hpxDcDOHvxgpV",
              "Email_Id": "ramesh.nagda79@gmail.com",
              "Status": "Not Sold"
            },
            {
              "Id": 25,
              "Player_Name": "Harsh Bipin Nagda",
              "Mobile_Number": 7738622896,
              "Location": "Nallasopara",
              "Village": "Godhra",
              "NPL1_NPL2": "Both",
              "Cricket_Type": "Allrounder",
              "TShirt_Size": "XXL",
              "Age": 30,
              "Gender": "Male",
              "Payment_SS": "https://drive.google.com/open?id=1KIRFrQbJAYH_ROtVxWAYhbZLQoEKxRwW",
              "Photo": "https://drive.google.com/open?id=1TE6kAeLCWraJ1-krpHlm8IXphXp2syHK",
              "Email_Id": "Baf.hbn@gmail.com",
              "Status": "Not Sold"
            },
            {
              "Id": 26,
              "Player_Name": "Chintan Virendra Nagda",
              "Mobile_Number": 9503164649,
              "Location": "Nallasopara",
              "Village": "Changdai",
              "NPL1_NPL2": "Both",
              "Cricket_Type": "Allrounder",
              "TShirt_Size": "L",
              "Age": 25,
              "Gender": "Male",
              "Payment_SS": "https://drive.google.com/open?id=1tWosVDCGAGq41sFnoO8I2LpaPIDaWu89",
              "Photo": "https://drive.google.com/open?id=1yXvvNH0-VlRFeVQKa-qr1Mi5k4GDYJqe",
              "Email_Id": "nagdachintan210@gmail.com",
              "Status": "Not Sold"
            },
            {
              "Id": 27,
              "Player_Name": "VAIBHAV NARESH NAGDA",
              "Mobile_Number": 9969540404,
              "Location": "BHANDUP",
              "Village": "DUMRA",
              "NPL1_NPL2": "NPL-2",
              "Cricket_Type": "Allrounder",
              "TShirt_Size": "XL",
              "Age": 31,
              "Gender": "Male",
              "Payment_SS": "https://drive.google.com/open?id=1FtuCMF_3TNbIbvtWM4v42a0ipwJ6XMrO",
              "Photo": "https://drive.google.com/open?id=1RbKINMcLy9aKG8u6gBOqtWMH-3RHdzcZ",
              "Email_Id": "vaibhavnnagda@gmail.com",
              "Status": "Not Sold"
            },
            {
              "Id": 28,
              "Player_Name": "Mehul P Shah / Nagda",
              "Mobile_Number": 9920679681,
              "Location": "Mulund",
              "Village": "Sanosara",
              "NPL1_NPL2": "Both",
              "Cricket_Type": "Allrounder",
              "TShirt_Size": "L",
              "Age": 44,
              "Gender": "Male",
              "Payment_SS": "https://drive.google.com/open?id=1ILJTRYqXK7z6UeUbQYkB8T9RxtGeNzW5",
              "Photo": "https://drive.google.com/open?id=1vCC00sFCQsgzJJ6wWDLfYl4lk_FhkS4W",
              "Email_Id": "onlymehul@gmail.com",
              "Status": "Not Sold"
            },
            {
              "Id": 29,
              "Player_Name": "Nilesh Nagda",
              "Mobile_Number": 8454978586,
              "Location": "Kalyan",
              "Village": "Bhojay",
              "NPL1_NPL2": "None",
              "Cricket_Type": "Allrounder",
              "TShirt_Size": "L",
              "Age": 48,
              "Gender": "Male",
              "Payment_SS": "https://drive.google.com/open?id=1GaR5v04B6889tLWlHUtroezQgzUTRZaR",
              "Photo": "https://drive.google.com/open?id=1Q5c4Vw5-mh_jN0ttOUUqWXhYHb3dI8GX",
              "Email_Id": "Nileshnagda25@gmail.com",
              "Status": "Not Sold"
            },
            {
              "Id": 30,
              "Player_Name": "Mehul suresh nagda",
              "Mobile_Number": 9821182188,
              "Location": "Dahisar",
              "Village": "Bhojay",
              "NPL1_NPL2": "None",
              "Cricket_Type": "Batting",
              "TShirt_Size": "XXL",
              "Age": 39,
              "Gender": "Male",
              "Payment_SS": "https://drive.google.com/open?id=1mNMr8YhYVnisNzZ4Slq4vzj2whJ_bxiv",
              "Photo": "https://drive.google.com/open?id=1RtDW_B4bi08V18yAehVwgxrQcKdvR92L",
              "Email_Id": "Mehuln_1984@yahoo.com",
              "Status": "Not Sold"
            },
            {
              "Id": 31,
              "Player_Name": "Keval Vallabhji Nagda",
              "Mobile_Number": 9096789096,
              "Location": "Mumbai",
              "Village": "Sanosara",
              "NPL1_NPL2": "None",
              "Cricket_Type": "Allrounder",
              "TShirt_Size": "XXL",
              "Age": 31,
              "Gender": "Male",
              "Payment_SS": "https://drive.google.com/open?id=1mYdHLyyB2OzlgdL9Q0nW7o_t38bXiZ-X",
              "Photo": "https://drive.google.com/open?id=1Z212L9xRS6nkenv3VXESoR7YUTbJJUDz",
              "Email_Id": "kevalnagda.1992@gmail.com",
              "Status": "Not Sold"
            },
            {
              "Id": 32,
              "Player_Name": "Rushabh Nagda",
              "Mobile_Number": 8082494675,
              "Location": "Dombivli",
              "Village": "Vidh",
              "NPL1_NPL2": "Both",
              "Cricket_Type": "Batting",
              "TShirt_Size": "L",
              "Age": 30,
              "Gender": "Male",
              "Payment_SS": "https://drive.google.com/open?id=14VEnFhH841mOEalhvkHLkYm4khGN3CVc",
              "Photo": "https://drive.google.com/open?id=1lbOW7lii0y_-OCgrWH45K5FiLWiJV3Ep",
              "Email_Id": "rushabh.n2610@gmail.com",
              "Status": "Not Sold"
            },
            {
              "Id": 33,
              "Player_Name": "Gaurav Tushar Shah",
              "Mobile_Number": 9137864117,
              "Location": "Kalyan",
              "Village": "Vidh",
              "NPL1_NPL2": "None",
              "Cricket_Type": "Batting",
              "TShirt_Size": "M",
              "Age": 21,
              "Gender": "Male",
              "Payment_SS": "https://drive.google.com/open?id=1n-IofkYyEpOlo4ak_DtlZE2Du5BNj8aM",
              "Photo": "https://drive.google.com/open?id=1EC-ptOd1ASxdi7KcJLawqg3MjY8c5UWX",
              "Email_Id": "gauravshah421306@gmail.com",
              "Status": "Not Sold"
            },
            {
              "Id": 34,
              "Player_Name": "Parth Harakchand Nagda",
              "Mobile_Number": 8082053932,
              "Location": "Mulund",
              "Village": "Vindh",
              "NPL1_NPL2": "NPL-2",
              "Cricket_Type": "Allrounder",
              "TShirt_Size": "L",
              "Age": 28,
              "Gender": "Male",
              "Payment_SS": "https://drive.google.com/open?id=1ChH8dATBcfZZzj3Pi1iy3Lea8vDTn7cv",
              "Photo": "https://drive.google.com/open?id=1as3o_f3GeaKjqDE7csuYnM3a1tj8lXMX",
              "Email_Id": "nparth1994@gmail.com",
              "Status": "Not Sold"
            },
            {
              "Id": 35,
              "Player_Name": "Lokesh Nagda",
              "Mobile_Number": 7666991833,
              "Location": "Dombivali",
              "Village": "Vidh",
              "NPL1_NPL2": "NPL-2",
              "Cricket_Type": "Batting",
              "TShirt_Size": "Xl",
              "Age": 34,
              "Gender": "Male",
              "Payment_SS": "https://drive.google.com/open?id=1IerOcvQmct8d9fXmbC85qBRa4nvsdVsh",
              "Photo": "https://drive.google.com/open?id=1sUiiv2oLz2EU4eGkbW7Ic6zb9rlz1YgC",
              "Email_Id": "Lokeshnagda10@ Gmail.com",
              "Status": "Not Sold"
            },
            {
              "Id": 36,
              "Player_Name": "Hardik Harakchand Nagda",
              "Mobile_Number": 9821684526,
              "Location": "Mulund",
              "Village": "Vidh",
              "NPL1_NPL2": "NPL-2",
              "Cricket_Type": "Allrounder",
              "TShirt_Size": "L",
              "Age": 33,
              "Gender": "Male",
              "Payment_SS": "https://drive.google.com/open?id=1Q2g5N2XU24rghWeGpsNzMpNWNSP217g6",
              "Photo": "https://drive.google.com/open?id=1H8V1ezPndqkHWVil7fExl85z17qzCxm0",
              "Email_Id": "nhardik2207@gmail.com",
              "Status": "Not Sold"
            },
            {
              "Id": 37,
              "Player_Name": "Jeet Naresh Nagda",
              "Mobile_Number": 9969752621,
              "Location": "Bhandup",
              "Village": "Dumra",
              "NPL1_NPL2": "NPL-2",
              "Cricket_Type": "Allrounder",
              "TShirt_Size": "XL",
              "Age": 28,
              "Gender": "Male",
              "Payment_SS": "https://drive.google.com/open?id=1MmeLMolA93hwxnPZ3d5jnzsmA6HW2kE4",
              "Photo": "https://drive.google.com/open?id=1tHTINvrqOpTyMEvcgkCHIZZzBceQLSm5",
              "Email_Id": "jeetnagda06@gmail.com",
              "Status": "Not Sold"
            },
            {
              "Id": 38,
              "Player_Name": "KEVIN DEVENDRA SHAH",
              "Mobile_Number": 9833372828,
              "Location": "PAREL",
              "Village": "BHISARA",
              "NPL1_NPL2": "NPL-1",
              "Cricket_Type": "Batting",
              "TShirt_Size": "L",
              "Age": 38,
              "Gender": "Male",
              "Payment_SS": "https://drive.google.com/open?id=1V6pSx173-oAdS1GXJR9Sv2uHWzX4eRwz",
              "Photo": "https://drive.google.com/open?id=1zmy8cFh-g0PL1L9CMomVbdFnjdBJnq-j",
              "Email_Id": "kevinshah123@gmail.com",
              "Status": "Not Sold"
            },
            {
              "Id": 39,
              "Player_Name": "Bhavya Anil Nagda",
              "Mobile_Number": 8356987695,
              "Location": "Kandivali East",
              "Village": "Karaghogha",
              "NPL1_NPL2": "Both",
              "Cricket_Type": "Allrounder",
              "TShirt_Size": "XXXL",
              "Age": 30,
              "Gender": "Male",
              "Payment_SS": "https://drive.google.com/open?id=1rrNHZ0j5D2sdBfU4_tjS6C2ZdzRee0qZ",
              "Photo": "https://drive.google.com/open?id=1tt0U0IVJFD6NJU9BxP-bHeYQWucQMzDM",
              "Email_Id": "bhavya100593@gmail.com",
              "Status": "Not Sold"
            },
            {
              "Id": 40,
              "Player_Name": "Palak Deepak Nagda",
              "Mobile_Number": "9757035034/9082618007",
              "Location": "Vikhroli",
              "Village": "Naredi",
              "NPL1_NPL2": "NPL-2",
              "Cricket_Type": "Bowling",
              "TShirt_Size": "XL",
              "Age": 27,
              "Gender": "Male",
              "Payment_SS": "https://drive.google.com/open?id=1eB8DHOxp_ga7bO3CBYDt_FD2PVRPpVtQ",
              "Photo": "https://drive.google.com/open?id=1PEIvzfbJzgVhhQPUg-kMah_Xp64RYFso",
              "Email_Id": "palaks639@gmail.com",
              "Status": "Not Sold"
            },
            {
              "Id": 41,
              "Player_Name": "Rohan Devendra shah / Nagda",
              "Mobile_Number": 9833592828,
              "Location": "MAZGAON",
              "Village": "Bhinsara",
              "NPL1_NPL2": "NPL-1",
              "Cricket_Type": "Allrounder",
              "TShirt_Size": "L",
              "Age": 36,
              "Gender": "Male",
              "Payment_SS": "https://drive.google.com/open?id=11iIqdFk4sqmOowl5pW1KxI45sq_yXrWx",
              "Photo": "https://drive.google.com/open?id=1CrGU1TKf4xbVlhUP09rwXYwXgs4hGxWR",
              "Email_Id": "Shahrohan87@gmail.com",
              "Status": "Not Sold"
            },
            {
              "Id": 42,
              "Player_Name": "Shasan Kirti Nagda",
              "Mobile_Number": 9960411881,
              "Location": "VASAI",
              "Village": "Naredi",
              "NPL1_NPL2": "None",
              "Cricket_Type": "Allrounder",
              "TShirt_Size": "Xxl",
              "Age": 24,
              "Gender": "Male",
              "Payment_SS": "https://drive.google.com/open?id=1LCgp2x7h_n8plROrP4MfqMO1sUuyUrHT",
              "Photo": "https://drive.google.com/open?id=1Q9o98_8EH6Ql6G0tyDQTdV-vTMhb1uo_",
              "Email_Id": "shasannagdag4@outlook.com",
              "Status": "Not Sold"
            },
            {
              "Id": 43,
              "Player_Name": "Pratik Devendra shah/Nagda",
              "Mobile_Number": 9869562077,
              "Location": "Mazgaon",
              "Village": "Bhisara",
              "NPL1_NPL2": "NPL-1",
              "Cricket_Type": "Allrounder",
              "TShirt_Size": "M",
              "Age": 35,
              "Gender": "Male",
              "Payment_SS": "https://drive.google.com/open?id=1RMN92YA06RFIhgJyXUhuZjsXGjhuX0Vq",
              "Photo": "https://drive.google.com/open?id=1oqcHxenbEdPy4XCToEZtNbS6YgPpyM_c",
              "Email_Id": "pratik06111988@gmail.com",
              "Status": "Not Sold"
            },
            {
              "Id": 44,
              "Player_Name": "Hiren Chhaganlal Shah / Nagda",
              "Mobile_Number": 8879881486,
              "Location": "Mazgaon",
              "Village": "Bhisara",
              "NPL1_NPL2": "NPL-1",
              "Cricket_Type": "Allrounder",
              "TShirt_Size": "L",
              "Age": 35,
              "Gender": "Male",
              "Payment_SS": "https://drive.google.com/open?id=1YVzUZTFxhtDMG5b9Qvaok_p_tMPN6VbT",
              "Photo": "https://drive.google.com/open?id=1xAAi__3S1fz5fWSzOyFshV63mtfSPO9V",
              "Email_Id": "hirenshah0613@gmail.com",
              "Status": "Not Sold"
            },
            {
              "Id": 45,
              "Player_Name": "Khamir Chhaganlal Shah/Nagda",
              "Mobile_Number": 9920893389,
              "Location": "Chembur",
              "Village": "Bhinsara",
              "NPL1_NPL2": "NPL-1",
              "Cricket_Type": "Allrounder",
              "TShirt_Size": "XL",
              "Age": 45,
              "Gender": "Male",
              "Payment_SS": "https://drive.google.com/open?id=1T7biwPKvny8loRrKplIaa85oixu2eH-j",
              "Photo": "https://drive.google.com/open?id=1otOIXsxO1OPGSC3W0rwSa3h2bMQrnDHD",
              "Email_Id": "khamirshah@gmail.com",
              "Status": "Not Sold"
            },
            {
              "Id": 46,
              "Player_Name": "Kushal Nagda",
              "Mobile_Number": 9082320566,
              "Location": "Kalwa",
              "Village": "Moti Undoth",
              "NPL1_NPL2": "NPL-2",
              "Cricket_Type": "Allrounder",
              "TShirt_Size": "xl",
              "Age": 24,
              "Gender": "Male",
              "Payment_SS": "https://drive.google.com/open?id=1iMbt765R6X_Y40cfJ8q4lxQtBhLJZHxi",
              "Photo": "https://drive.google.com/open?id=1tXhICxkmhLjsi3zFEaceEyLQA3sH-WOp",
              "Email_Id": "onlytraders777@gmail.com",
              "Status": "Not Sold"
            },
            {
              "Id": 47,
              "Player_Name": "Sunny Ramnik Nagda",
              "Mobile_Number": "9930534071/9082897113",
              "Location": "Mulund",
              "Village": "Naredi",
              "NPL1_NPL2": "Both",
              "Cricket_Type": "Allrounder",
              "TShirt_Size": "3xl",
              "Age": 27,
              "Gender": "Male",
              "Payment_SS": "https://drive.google.com/open?id=1FTrlBHTOif1RoLyzqruk_632H1ZDT22x",
              "Photo": "https://drive.google.com/open?id=14aA8s_CaSFMSLl9y03JjciI2hqVuQ5Cd",
              "Email_Id": "sunnagda11@gmail.com",
              "Status": "Not Sold"
            },
            {
              "Id": 48,
              "Player_Name": "Aaryan Ketan Nagda",
              "Mobile_Number": 8799249092,
              "Location": "Thane",
              "Village": "Sanosara",
              "NPL1_NPL2": "Both",
              "Cricket_Type": "Batting",
              "TShirt_Size": "Xxl",
              "Age": 20,
              "Gender": "Male",
              "Payment_SS": "https://drive.google.com/open?id=1em0DbWmtf5PFxATrU_Aav2aNckoSb-pb",
              "Photo": "https://drive.google.com/open?id=1Liqar1RoxSJYv5S2z2etJiIqcapC_w9i",
              "Email_Id": "aaryanshah003@gmail.com",
              "Status": "Not Sold"
            },
            {
              "Id": 49,
              "Player_Name": "Piyush Manilal Nagda",
              "Mobile_Number": 9867935665,
              "Location": "Bhandup",
              "Village": "Kotdi mahadev puri",
              "NPL1_NPL2": "Both",
              "Cricket_Type": "Bowling",
              "TShirt_Size": "M",
              "Age": 49,
              "Gender": "Male",
              "Payment_SS": "https://drive.google.com/open?id=1ZUBY11iEY_Xhm3ygqNs5wseDr3voamKk",
              "Photo": "https://drive.google.com/open?id=1zYwk3OyetmSuMiWAGdJH0snEVYHphO8j",
              "Email_Id": "piyushnagda74@gmail.com",
              "Status": "Not Sold"
            },
            {
              "Id": 50,
              "Player_Name": "Jay Rajesh Nagda",
              "Mobile_Number": 9323125077,
              "Location": "Sanpada",
              "Village": "Sanosara",
              "NPL1_NPL2": "NPL-2",
              "Cricket_Type": "Allrounder",
              "TShirt_Size": "M",
              "Age": 18,
              "Gender": "Male",
              "Payment_SS": "https://drive.google.com/open?id=16yl3zP6gsn2HUBv_nRI-F1mxiTtRtTSW",
              "Photo": "https://drive.google.com/open?id=1wK5HvQAo5WZTLsf5ur0YvmgKfEbJjQKU",
              "Email_Id": "jayrnagda@gmail.com",
              "Status": "Not Sold"
            },
            {
              "Id": 51,
              "Player_Name": "Jugal Mahendra Nagda",
              "Mobile_Number": 8451901381,
              "Location": "Nahur",
              "Village": "Vidh",
              "NPL1_NPL2": "NPL-2",
              "Cricket_Type": "Batting",
              "TShirt_Size": "XL",
              "Age": 30,
              "Gender": "Male",
              "Payment_SS": "https://drive.google.com/open?id=1648Xl_gE1tF8FTbbhfAfaE-DQTN1TB2p",
              "Photo": "https://drive.google.com/open?id=1M8iPPspVvnqbWNPWelJr73zfXcdIcEHC",
              "Email_Id": "JUGAL.NAGDA@GMAIL.COM",
              "Status": "Not Sold"
            },
            {
              "Id": 52,
              "Player_Name": "Keval Nagda",
              "Mobile_Number": 8104759930,
              "Location": "Thane",
              "Village": "Dhediya",
              "NPL1_NPL2": "Both",
              "Cricket_Type": "Allrounder",
              "TShirt_Size": "M",
              "Age": 26,
              "Gender": "Male",
              "Payment_SS": "https://drive.google.com/open?id=1wxsre6OKdRt33TQdtBOO-huqCOQFsiUE",
              "Photo": "https://drive.google.com/open?id=1sZ1Z3tC6wUtEbn3NUjB3GiYCI5x5aTpR",
              "Email_Id": "kevalnagda2512@gmail.com",
              "Status": "Not Sold"
            },
            {
              "Id": 53,
              "Player_Name": "Dhruv Vinesh Nagda",
              "Mobile_Number": 8356046150,
              "Location": "Mulund",
              "Village": "Sanosara",
              "NPL1_NPL2": "NPL-2",
              "Cricket_Type": "Allrounder",
              "TShirt_Size": "M",
              "Age": 18,
              "Gender": "Male",
              "Payment_SS": "https://drive.google.com/open?id=16RpsbVbGIJd-7JhTQFoxn7GSV1sy81vg",
              "Photo": "https://drive.google.com/open?id=1_aDL4igfbZ0laMk34EhLujeC3qtdJXUH",
              "Email_Id": "dhruvnagda05@gmail.com",
              "Status": "Not Sold"
            },
            {
              "Id": 54,
              "Player_Name": "Paras hiralal shah/ nagda",
              "Mobile_Number": 9324928147,
              "Location": "Ambernath",
              "Village": "Naredi",
              "NPL1_NPL2": "None",
              "Cricket_Type": "Allrounder",
              "TShirt_Size": "XXL",
              "Age": 44,
              "Gender": "Male",
              "Payment_SS": "https://drive.google.com/open?id=1hgyv_DP7nts7_PRnj_m-qnFl8v_R3tlX",
              "Photo": "https://drive.google.com/open?id=1_g7_JsKksufcp2B7Zx7sY6Oy-4-wGq_1",
              "Email_Id": "Shahparas744@gmail.com",
              "Status": "Not Sold"
            },
            {
              "Id": 55,
              "Player_Name": "Urvil Deepak Nagda",
              "Mobile_Number": 7039509323,
              "Location": "Kalwa",
              "Village": "Moti Undoth",
              "NPL1_NPL2": "NPL-2",
              "Cricket_Type": "Allrounder",
              "TShirt_Size": "L",
              "Age": 22,
              "Gender": "Male",
              "Payment_SS": "https://drive.google.com/open?id=1CaMpc2AQ862-bppFy1K9vG1LfCMVt6-3",
              "Photo": "https://drive.google.com/open?id=1--ZfiAK2l94lBBGm0gDdDVT0ubbv88uV",
              "Email_Id": "urvilnagda11@gmail.com",
              "Status": "Not Sold"
            },
            {
              "Id": 56,
              "Player_Name": "Bhavesh Rasik Nagda",
              "Mobile_Number": 9987407527,
              "Location": "Vashi",
              "Village": "Changdai",
              "NPL1_NPL2": "NPL-1",
              "Cricket_Type": "Allrounder",
              "TShirt_Size": "M",
              "Age": 37,
              "Gender": "Male",
              "Payment_SS": "https://drive.google.com/open?id=1o-jfc3H6ufEH-MP7PXZFoCvcGN0YB2DJ",
              "Photo": "https://drive.google.com/open?id=1mjfwMybtmodarEU_NVA3R4J3F1mRSvyP",
              "Email_Id": "bhaveshrnagda@gmail.com",
              "Status": "Not Sold"
            },
            {
              "Id": 57,
              "Player_Name": "Javerchand Khimji Nagda",
              "Mobile_Number": 7738141333,
              "Location": "Santacruz",
              "Village": "Bhojay",
              "NPL1_NPL2": "Both",
              "Cricket_Type": "Allrounder",
              "TShirt_Size": "M",
              "Age": 62,
              "Gender": "Male",
              "Payment_SS": "https://drive.google.com/open?id=1g7LDuMvJKlA1Y0xKCqHXxqwLkXYpEbwf",
              "Photo": "https://drive.google.com/open?id=1bfWcXL_Jq_Fj1VqjH1HnwjKK0ZJBYPET",
              "Email_Id": "javerchand11@gmail.com",
              "Status": "Not Sold"
            },
            {
              "Id": 58,
              "Player_Name": "Paras Gulab Nagda",
              "Mobile_Number": 9820399970,
              "Location": "Borivali",
              "Village": "Bhojay",
              "NPL1_NPL2": "NPL-2",
              "Cricket_Type": "Allrounder",
              "TShirt_Size": "XXL",
              "Age": 42,
              "Gender": "Male",
              "Payment_SS": "https://drive.google.com/open?id=1UYNAaZJCuQDMUbpfdJqOvNNi2_I7UXzr",
              "Photo": "https://drive.google.com/open?id=1PV0xEVME-cEHYfMq9QJeKs4q186B6z6G",
              "Email_Id": "parasnagda@gmail.com",
              "Status": "Not Sold"
            },
            {
              "Id": 59,
              "Player_Name": "Harshal Girish Nagda",
              "Mobile_Number": 9029370343,
              "Location": "Nalasopara",
              "Village": "Bhojay",
              "NPL1_NPL2": "None",
              "Cricket_Type": "Allrounder",
              "TShirt_Size": "M",
              "Age": 18,
              "Gender": "Male",
              "Payment_SS": "https://drive.google.com/open?id=1O1mhVqkY2nW5zKWzkVcUG7CSBQ9Z5WKl",
              "Photo": "https://drive.google.com/open?id=1eO3FJGzewYrx-zBJ1QRIGLz8aIZ18kpl",
              "Email_Id": "harshalnagda39@gmail.com",
              "Status": "Not Sold"
            },
            {
              "Id": 60,
              "Player_Name": "Naman Lalit Jain",
              "Mobile_Number": 7620806592,
              "Location": "Ambernath",
              "Village": "Chanagdai",
              "NPL1_NPL2": "NPL-2",
              "Cricket_Type": "Allrounder",
              "TShirt_Size": "XL",
              "Age": 23,
              "Gender": "Male",
              "Payment_SS": "https://drive.google.com/open?id=1tRBV6pm2G6prhnamRsb2-5ZqoVUtDxnJ",
              "Photo": "https://drive.google.com/open?id=1C31R66luxZp3SvN0aoIZqgBUKD5tFolN",
              "Email_Id": "mr.nmjain786@gmail.com",
              "Status": "Not Sold"
            },
            {
              "Id": 61,
              "Player_Name": "Ramesh Meghji Shah/Nagda",
              "Mobile_Number": 8591269008,
              "Location": "Borivali",
              "Village": "Kapaya",
              "NPL1_NPL2": "NPL-1",
              "Cricket_Type": "Allrounder",
              "TShirt_Size": "XL",
              "Age": 62,
              "Gender": "Male",
              "Payment_SS": "https://drive.google.com/open?id=1Ttfq78iar6oCdkGfjQDQ-ObDH0rH1Qog",
              "Photo": "https://drive.google.com/open?id=1Hb4Ed99mKq7JNoo7gdonDHtnwFURJhBp",
              "Email_Id": "rameshshah59234@gmail.com",
              "Status": "Not Sold"
            },
            {
              "Id": 62,
              "Player_Name": "Hitendra devraj Nagda",
              "Mobile_Number": 9920228841,
              "Location": "Dombivli",
              "Village": "Sanosara",
              "NPL1_NPL2": "NPL-2",
              "Cricket_Type": "Allrounder",
              "TShirt_Size": "Xxl",
              "Age": 45,
              "Gender": "Male",
              "Payment_SS": "https://drive.google.com/open?id=1BplyRiltDP5Pxgq1BnikyOJZmLSObHmk",
              "Photo": "https://drive.google.com/open?id=1nmnRCUOmnuU0FR3ftinhMPzGG8G61iTf",
              "Email_Id": "hitendranagda2@gmail.com",
              "Status": "Not Sold"
            },
            {
              "Id": 63,
              "Player_Name": "Rupesh Manilal Nagda",
              "Mobile_Number": 9819656574,
              "Location": "Bhayandar",
              "Village": "Naredi",
              "NPL1_NPL2": "Both",
              "Cricket_Type": "Allrounder",
              "TShirt_Size": "XXL",
              "Age": 46,
              "Gender": "Male",
              "Payment_SS": "https://drive.google.com/open?id=1gC41foMH_8s9bbFwIgGV8ih_8ZLXgOl0",
              "Photo": "https://drive.google.com/open?id=182vIOpEHT-hpEAoWRlkLxHQbWAQcEat5",
              "Email_Id": "rupesh_nagda@yahoo.com",
              "Status": "Not Sold"
            },
            {
              "Id": 64,
              "Player_Name": "Anil Jayantilal Nagda",
              "Mobile_Number": 9820171414,
              "Location": "Tardeo",
              "Village": "Kotdi Mahadevpuri",
              "NPL1_NPL2": "Both",
              "Cricket_Type": "Bowling",
              "TShirt_Size": "L",
              "Age": 46,
              "Gender": "Male",
              "Payment_SS": "https://drive.google.com/open?id=1ckdd2OOZYv8vGYAua0ViKEtLOpzVFeIo",
              "Photo": "https://drive.google.com/open?id=1XFRZRWcAVxHY-0rJpAuBINE7tHqUNmK4",
              "Email_Id": "anil71414@gmail.com",
              "Status": "Not Sold"
            },
            {
              "Id": 65,
              "Player_Name": "Param Piyush Nagda",
              "Mobile_Number": 9702223335,
              "Location": "Goregaon",
              "Village": "Sanosara",
              "NPL1_NPL2": "None",
              "Cricket_Type": "Allrounder",
              "TShirt_Size": "Xxl",
              "Age": 23,
              "Gender": "Male",
              "Payment_SS": "https://drive.google.com/open?id=1UjChkPA_lX2Cw4jPjO4tnvRjabYBb-wx",
              "Photo": "https://drive.google.com/open?id=1kT4rmKZFcRWmTKUB5Q-ojo1yM52-DMoW",
              "Email_Id": "nagdaparam22@gmail.com",
              "Status": "Not Sold"
            },
            {
              "Id": 66,
              "Player_Name": "Vishal Navin Nagda",
              "Mobile_Number": 9892499900,
              "Location": "Mira road",
              "Village": "Gadhshisha",
              "NPL1_NPL2": "Both",
              "Cricket_Type": "Allrounder",
              "TShirt_Size": "XL",
              "Age": 42,
              "Gender": "Male",
              "Payment_SS": "https://drive.google.com/open?id=1pA2U2KuWc12U8NWyqGOFnZm0t5xh4xnD",
              "Photo": "https://drive.google.com/open?id=11a-Ql8niOyv35uE9KEIn5FfgDw95hIgs",
              "Email_Id": "vishalnagda163@gmail.com",
              "Status": "Not Sold"
            },
            {
              "Id": 67,
              "Player_Name": "Sanket Laxmichand Nagda",
              "Mobile_Number": 9152505002,
              "Location": "Dombivali",
              "Village": "Kotda Roha",
              "NPL1_NPL2": "NPL-2",
              "Cricket_Type": "Allrounder",
              "TShirt_Size": "M",
              "Age": 33,
              "Gender": "Male",
              "Payment_SS": "https://drive.google.com/open?id=1UH_eCMtF5zThpsGwLmPdeJITQcaSfu5K",
              "Photo": "https://drive.google.com/open?id=1M39REkIenkmy1maNutUnHrpIBANollm6",
              "Email_Id": "sanketnagda411@gmail.com",
              "Status": "Not Sold"
            },
            {
              "Id": 68,
              "Player_Name": "Bhavesh kantilal Nagda",
              "Mobile_Number": 9820979760,
              "Location": "Mulund east",
              "Village": "Sanosara",
              "NPL1_NPL2": "Both",
              "Cricket_Type": "Allrounder",
              "TShirt_Size": "XL",
              "Age": 52,
              "Gender": "Male",
              "Payment_SS": "https://drive.google.com/open?id=1dTdxugV63ivVijoL8oBXP0swfydvrDOa",
              "Photo": "https://drive.google.com/open?id=1nIYaHMh0IIr1Iojf9vXSP1PTex2-3l_C",
              "Email_Id": "bhaveshknagda@gmail.com",
              "Status": "Not Sold"
            },
            {
              "Id": 69,
              "Player_Name": "Bhavin Hiralal Nagda",
              "Mobile_Number": 9594040648,
              "Location": "Bhayandar west",
              "Village": "Moti Undoth",
              "NPL1_NPL2": "NPL-2",
              "Cricket_Type": "Allrounder",
              "TShirt_Size": "XL",
              "Age": 38,
              "Gender": "Male",
              "Payment_SS": "https://drive.google.com/open?id=1G0NwjUvVNFmqBsMmvMiUFVzxNuvY1zNv",
              "Photo": "https://drive.google.com/open?id=1-TfIp_lY9AGgu4a2bgsgCOp-q4305bBJ",
              "Email_Id": "bhavin.nagda2004@gmail.com",
              "Status": "Not Sold"
            },
            {
              "Id": 70,
              "Player_Name": "GIRISH JAGSHI NAGDA",
              "Mobile_Number": 9867972576,
              "Location": "Miraroad",
              "Village": "BHISARA",
              "NPL1_NPL2": "Both",
              "Cricket_Type": "Batting",
              "TShirt_Size": "M",
              "Age": 49,
              "Gender": "Male",
              "Payment_SS": "https://drive.google.com/open?id=1Be945WLt6ActI0-WCOxUqOm2xtlUiPyA",
              "Photo": "https://drive.google.com/open?id=140ckA6H38SPbPNj_Cynt-0VYxO04bOIs",
              "Email_Id": "Shah1989girish@gmail.com",
              "Status": "Not Sold"
            },
            {
              "Id": 71,
              "Player_Name": "Rohan praful nagda",
              "Mobile_Number": 9819437111,
              "Location": "Thane",
              "Village": "Kotdi mahadevpuri",
              "NPL1_NPL2": "NPL-2",
              "Cricket_Type": "Batting",
              "TShirt_Size": "XXXL",
              "Age": 36,
              "Gender": "Male",
              "Payment_SS": "https://drive.google.com/open?id=1rKyi-HSigHULIPPSF8Crj3qwA4kFSESg",
              "Photo": "https://drive.google.com/open?id=1DLZwJuXMoCO35KatuS47I7zxpYFvd0yC",
              "Email_Id": "rohannagda8@gmail.com",
              "Status": "Not Sold"
            },
            {
              "Id": 72,
              "Player_Name": "Rushabh Navin Nagda",
              "Mobile_Number": 9323232000,
              "Location": "Juhu",
              "Village": "Changdai",
              "NPL1_NPL2": "Both",
              "Cricket_Type": "Batting",
              "TShirt_Size": "L",
              "Age": 23,
              "Gender": "Male",
              "Payment_SS": "https://drive.google.com/open?id=1isVhC5lHGT9Y9QJ6Ty0XeAcjkgw6p04t",
              "Photo": "https://drive.google.com/open?id=116wANPhXSbTHocTF-SFYRVGfL867fRBb",
              "Email_Id": "rushabhnagda49@gmail.com",
              "Status": "Not Sold"
            },
            {
              "Id": 73,
              "Player_Name": "RITESH JAGDISH NAGDA",
              "Mobile_Number": 9222133618,
              "Location": "BHANDUP",
              "Village": "MITI UNDOTH",
              "NPL1_NPL2": "NPL-2",
              "Cricket_Type": "Allrounder",
              "TShirt_Size": "XL",
              "Age": 34,
              "Gender": "Male",
              "Payment_SS": "https://drive.google.com/open?id=1qML0LSElUtysP_WtNqcvuIveFaKiKGBS",
              "Photo": "https://drive.google.com/open?id=189UYFDVwkcqnFwLr--nZYQOoL2HHfw7u",
              "Email_Id": "nritesh@yahoo.com",
              "Status": "Not Sold"
            },
            {
              "Id": 74,
              "Player_Name": "SACHIN JAGDISH NAGDA",
              "Mobile_Number": 9224696075,
              "Location": "BHANDUP",
              "Village": "MOTI UNDOTH",
              "NPL1_NPL2": "Both",
              "Cricket_Type": "Allrounder",
              "TShirt_Size": "XL",
              "Age": 34,
              "Gender": "Male",
              "Payment_SS": "https://drive.google.com/open?id=1iCQBkVxu6_BD45iJ2uhtqkrsJrRXudTd",
              "Photo": "https://drive.google.com/open?id=1hjyydpCScGb7ndupIQ17stAONPxJhf3F",
              "Email_Id": "nritesh@yahoo.com",
              "Status": "Not Sold"
            },
            {
              "Id": 75,
              "Player_Name": "Chaitanya Vikram Nagda",
              "Mobile_Number": 9326035659,
              "Location": "Chembur",
              "Village": "Naredi",
              "NPL1_NPL2": "None",
              "Cricket_Type": "Bowling",
              "TShirt_Size": "L",
              "Age": 18,
              "Gender": "Male",
              "Payment_SS": "https://drive.google.com/open?id=17wOUC3xKPOYNBsM5xTIMARlkoLrlAL-S",
              "Photo": "https://drive.google.com/open?id=1st5uYMi2L8qKQZ2JUXaHh7uyw9sp5BVu",
              "Email_Id": "cvnindia99@gmail.com",
              "Status": "Not Sold"
            },
            {
              "Id": 76,
              "Player_Name": "Varun Jitendra Shah/Nagda",
              "Mobile_Number": 9819749009,
              "Location": "Santacruz",
              "Village": "Layja",
              "NPL1_NPL2": "Both",
              "Cricket_Type": "Allrounder",
              "TShirt_Size": "L",
              "Age": 34,
              "Gender": "Male",
              "Payment_SS": "https://drive.google.com/open?id=1-Kbmyo0WpT2gidJ8y6G4bClexQIhO9EG",
              "Photo": "https://drive.google.com/open?id=1EB2DVXP6CpsoZBGmXIlUN3ZXcFRzV0t_",
              "Email_Id": "varu009.vs@gmail.com",
              "Status": "Not Sold"
            },
            {
              "Id": 77,
              "Player_Name": "Parth Ramesh Nagda",
              "Mobile_Number": 9920449945,
              "Location": "Bhandup",
              "Village": "Bhojay",
              "NPL1_NPL2": "Both",
              "Cricket_Type": "Allrounder",
              "TShirt_Size": "L",
              "Age": 25,
              "Gender": "Male",
              "Payment_SS": "https://drive.google.com/open?id=1DRUJiFtYEhWeTnCsQVR555JDAPM-eZK3",
              "Photo": "https://drive.google.com/open?id=1Xqi93xAIzwzQgp3TmHVzGk08rSlghtId",
              "Email_Id": "pnagda71@gmail.com",
              "Status": "Not Sold"
            },
            {
              "Id": 78,
              "Player_Name": "Biren Pravin Nagda",
              "Mobile_Number": 9004071455,
              "Location": "Bhandup",
              "Village": "Sanosara",
              "NPL1_NPL2": "Both",
              "Cricket_Type": "Batting",
              "TShirt_Size": "L",
              "Age": 39,
              "Gender": "Male",
              "Payment_SS": "https://drive.google.com/open?id=1PgwKz0Vc-n9z2AwtjgwJtj3NA8PhlL7w",
              "Photo": "https://drive.google.com/open?id=1ao3HL7iApu4E3oqoTdsq1HgNcjdieqke",
              "Email_Id": "biren.nagda@gmail.com",
              "Status": "Not Sold"
            },
            {
              "Id": 79,
              "Player_Name": "Mehul Vishanji Nagda",
              "Mobile_Number": 9820489899,
              "Location": "Bhandup",
              "Village": "Lathedi",
              "NPL1_NPL2": "Both",
              "Cricket_Type": "Bowling",
              "TShirt_Size": "Xl",
              "Age": 47,
              "Gender": "Male",
              "Payment_SS": "https://drive.google.com/open?id=1YPePqWttSEe_WUelLS4s9i9fo92c82Me",
              "Photo": "https://drive.google.com/open?id=1IL-mmnHUcLZ7P3-ysIOsCn98cdVfAsbH",
              "Email_Id": "mehul.nagda@yahoo.com",
              "Status": "Not Sold"
            },
            {
              "Id": 80,
              "Player_Name": "Akshay Rajnikant Nagda",
              "Mobile_Number": 9920365522,
              "Location": "Mulund",
              "Village": "Naredi",
              "NPL1_NPL2": "NPL-2",
              "Cricket_Type": "Allrounder",
              "TShirt_Size": "M",
              "Age": 41,
              "Gender": "Male",
              "Payment_SS": "https://drive.google.com/open?id=1IwAdHaZas_x6GNfzryRPvhpwhLS0FAVn",
              "Photo": "https://drive.google.com/open?id=1gCAQQX4TrxJVMxhh56zKWSLA8Ljdnm8U",
              "Email_Id": "starent2008@gmail.com",
              "Status": "Not Sold"
            },
            {
              "Id": 81,
              "Player_Name": "SMIT ZAVERCHAND NAGDA",
              "Mobile_Number": 9920751443,
              "Location": "DOMBIVLI",
              "Village": "CHANGDAI",
              "NPL1_NPL2": "NPL-2",
              "Cricket_Type": "Allrounder",
              "TShirt_Size": "M",
              "Age": 30,
              "Gender": "Male",
              "Payment_SS": "https://drive.google.com/open?id=1lIF0qa9xu8TqFl2wF94vq8lhiRPwDFkl",
              "Photo": "https://drive.google.com/open?id=1RjUXMQ0K3FT0f8vrXf21kOv40j_qZLm1",
              "Email_Id": "smit.nagda50@gmail.com",
              "Status": "Not Sold"
            },
            {
              "Id": 82,
              "Player_Name": "DIPESH HIRJI NAGDA",
              "Mobile_Number": 8411042068,
              "Location": "Ambernath",
              "Village": "NAREDI",
              "NPL1_NPL2": "Both",
              "Cricket_Type": "Bowling",
              "TShirt_Size": "M",
              "Age": 38,
              "Gender": "Male",
              "Payment_SS": "https://drive.google.com/open?id=1sARbBAkjJcP2eiTiQjQKL72Y9ipnrRWX",
              "Photo": "https://drive.google.com/open?id=14nJM1VsIMrPHk_M71u4MDH1MqCEm6iTK",
              "Email_Id": "dipeshnagda9785@gmail.com",
              "Status": "Not Sold"
            },
            {
              "Id": 83,
              "Player_Name": "Nilesh hirji nagda",
              "Mobile_Number": 9673040061,
              "Location": "Ambarnath",
              "Village": "Naredi",
              "NPL1_NPL2": "Both",
              "Cricket_Type": "Allrounder",
              "TShirt_Size": "Xl",
              "Age": 35,
              "Gender": "Male",
              "Payment_SS": "https://drive.google.com/open?id=14XHV6WHJ3b03AAjcJVhXy3WASL_k3F_o",
              "Photo": "https://drive.google.com/open?id=1z6hJjftdjm7gMkeGCdIE2eyCCVDWH8IH",
              "Email_Id": "nileshnagda5189@gmail.com",
              "Status": "Not Sold"
            },
            {
              "Id": 84,
              "Player_Name": "Rohan Vijay Nagda",
              "Mobile_Number": 8652672112,
              "Location": "Dombivli",
              "Village": "Kotdi",
              "NPL1_NPL2": "Both",
              "Cricket_Type": "Allrounder",
              "TShirt_Size": "L-40",
              "Age": 19,
              "Gender": "Male",
              "Payment_SS": "https://drive.google.com/open?id=16lpVXwMHk40OORT7TvCeYzL-ZAU70f1Z",
              "Photo": "https://drive.google.com/open?id=1fEiFw4w4ctAKv8PiUsaldb7-a1OZZDQ_",
              "Email_Id": "rohannagda074gmail.com",
              "Status": "Not Sold"
            },
            {
              "Id": 85,
              "Player_Name": "Chandresh Prabodh Nagda",
              "Mobile_Number": 9967781185,
              "Location": "Bhandup",
              "Village": "Moti Unodth",
              "NPL1_NPL2": "NPL-2",
              "Cricket_Type": "Batting",
              "TShirt_Size": "3XL",
              "Age": 40,
              "Gender": "Male",
              "Payment_SS": "https://drive.google.com/open?id=1rwxCxCU1-23Vlapj4plEQJFho2hw_Zh6",
              "Photo": "https://drive.google.com/open?id=16JIevXTs3I39WYTeMbIYFEXuDsi13zxs",
              "Email_Id": "phgala05@gmail.com",
              "Status": "Not Sold"
            },
            {
              "Id": 86,
              "Player_Name": "Mitesh prabodh nagda",
              "Mobile_Number": 9224130992,
              "Location": "Bhandup",
              "Village": "Moti Undoth",
              "NPL1_NPL2": "NPL-2",
              "Cricket_Type": "Allrounder",
              "TShirt_Size": "M",
              "Age": 35,
              "Gender": "Male",
              "Payment_SS": "https://drive.google.com/open?id=1PknWuqs-_H0lA7x3ebVUvo6Peapw23Zt",
              "Photo": "https://drive.google.com/open?id=1QHniTzIg59HJwueyxqbU7rUseaMZuy3x",
              "Email_Id": "phgala13@gmail.com",
              "Status": "Not Sold"
            },
            {
              "Id": 87,
              "Player_Name": "Bhavin Hemendra Nagda",
              "Mobile_Number": 9930098912,
              "Location": "Mulund",
              "Village": "Lathedi",
              "NPL1_NPL2": "Both",
              "Cricket_Type": "Allrounder",
              "TShirt_Size": "XXL (42)",
              "Age": 43,
              "Gender": "Male",
              "Payment_SS": "https://drive.google.com/open?id=1zjYcziKDdE05zmtmu6s9lUFm4xKY6Mau",
              "Photo": "https://drive.google.com/open?id=1smTv2iwsIIZmKwTV27ch7hI4sihKCoQj",
              "Email_Id": "bhavinnagda@gmail.com",
              "Status": "Not Sold"
            },
            {
              "Id": 88,
              "Player_Name": "Chintan Jitendra Shah/Nagda",
              "Mobile_Number": 9820361233,
              "Location": "Santacruz",
              "Village": "Mota Layja",
              "NPL1_NPL2": "Both",
              "Cricket_Type": "Bowling",
              "TShirt_Size": "L",
              "Age": 31,
              "Gender": "Male",
              "Payment_SS": "https://drive.google.com/open?id=1CXp6pivzXHxdnB4qg3xqyWhqlgVMLosY",
              "Photo": "https://drive.google.com/open?id=1uDfhGEQVOIqe25-mBm8jEvZ6rVLy2Eha",
              "Email_Id": "Chintanshah9429@gmail.com",
              "Status": "Not Sold"
            },
            {
              "Id": 89,
              "Player_Name": "Jitendra Shamji Shah/Nagda",
              "Mobile_Number": 9820429205,
              "Location": "Santacruz",
              "Village": "Mota Layja",
              "NPL1_NPL2": "NPL-1",
              "Cricket_Type": "Allrounder",
              "TShirt_Size": "XXL",
              "Age": 59,
              "Gender": "Male",
              "Payment_SS": "https://drive.google.com/open?id=1zJ1V8-iTSy4Q6rql12MTLFZ2FFP3SAnR",
              "Photo": "https://drive.google.com/open?id=1tuPdZHkL7ph0j_cCepwLf0yG_jX2cuWf",
              "Email_Id": "Vre9999@gmail.com",
              "Status": "Not Sold"
            },
            {
              "Id": 90,
              "Player_Name": "Dheer Rajesh Nagda",
              "Mobile_Number": 8655703843,
              "Location": "Mulund",
              "Village": "Makda",
              "NPL1_NPL2": "None",
              "Cricket_Type": "Allrounder",
              "TShirt_Size": "XXL",
              "Age": 22,
              "Gender": "Male",
              "Payment_SS": "https://drive.google.com/open?id=1y8VBcNe9E3fRsIkbnq3NM97y4z5WXPhL",
              "Photo": "https://drive.google.com/open?id=1VW_bGe_zaEyGuiO-pqOlnh83o4_4h_EC",
              "Email_Id": "dheern123@gmail.com",
              "Status": "Not Sold"
            },
            {
              "Id": 91,
              "Player_Name": "Harsh Ashish Nagda",
              "Mobile_Number": 7208344717,
              "Location": "Mulund(W)",
              "Village": "Naredi",
              "NPL1_NPL2": "Both",
              "Cricket_Type": "Allrounder",
              "TShirt_Size": "L",
              "Age": 17,
              "Gender": "Male",
              "Payment_SS": "https://drive.google.com/open?id=1_Dt0sD6JgKCp2GAYB6F9dh7JaTkAnsO5",
              "Photo": "https://drive.google.com/open?id=1LUe-uFNMMCaZanrNGnjqL9r1mrtztGrz",
              "Email_Id": "harshnagda0007@gmail.com",
              "Status": "Not Sold"
            },
            {
              "Id": 92,
              "Player_Name": "Jayesh Lakhamsi Nagda",
              "Mobile_Number": 8007317617,
              "Location": "Vasai",
              "Village": "Sanosara",
              "NPL1_NPL2": "Both",
              "Cricket_Type": "Bowling",
              "TShirt_Size": "XXL",
              "Age": 42,
              "Gender": "Male",
              "Payment_SS": "https://drive.google.com/open?id=1WVs3L40zwZJm0qV27l5NOxKDjS-fwheQ",
              "Photo": "https://drive.google.com/open?id=1zJZRwm774f6BBNxN8D2LXd2PHuraCph2",
              "Email_Id": "jayeshnagda78@gmail.com",
              "Status": "Not Sold"
            },
            {
              "Id": 93,
              "Player_Name": "Rajesh devchand Nagda",
              "Mobile_Number": 8291980836,
              "Location": "Mulund",
              "Village": "Naradi",
              "NPL1_NPL2": "Both",
              "Cricket_Type": "Batting",
              "TShirt_Size": "Xxl",
              "Age": 41,
              "Gender": "Male",
              "Payment_SS": "https://drive.google.com/open?id=1Ugeg-NtzHnB02AVQBTomrvhPivYUPwJB",
              "Photo": "https://drive.google.com/open?id=1bsEVn935P6J-cI4idfDV4A5wgqp6gMUi",
              "Email_Id": "rnagda359@gmail.com",
              "Status": "Not Sold"
            },
            {
              "Id": 94,
              "Player_Name": "Tusmit Naresh Shah",
              "Mobile_Number": 7039738033,
              "Location": "Dombivli",
              "Village": "Bhojay",
              "NPL1_NPL2": "NPL-2",
              "Cricket_Type": "Allrounder",
              "TShirt_Size": "L",
              "Age": 23,
              "Gender": "Male",
              "Payment_SS": "Committee",
              "Photo": "",
              "Email_Id": "tusmitshah@gmail.com",
              "Status": "Not Sold"
            },
            {
              "Id": 95,
              "Player_Name": "Vijay Mulchand Nagda",
              "Mobile_Number": 7045312026,
              "Location": "Dombivli",
              "Village": "Bhojay",
              "NPL1_NPL2": "Both",
              "Cricket_Type": "Allrounder",
              "TShirt_Size": "",
              "Age": "",
              "Gender": "Male",
              "Payment_SS": "Committee",
              "Photo": "",
              "Email_Id": "",
              "Status": "Not Sold"
            },
            {
              "Id": 96,
              "Player_Name": "Chirag Dilip Nagda",
              "Mobile_Number": 9769979745,
              "Location": "Mulund",
              "Village": "Vidh",
              "NPL1_NPL2": "Both",
              "Cricket_Type": "Allrounder",
              "TShirt_Size": "XL",
              "Age": 35,
              "Gender": "Male",
              "Payment_SS": "Committee",
              "Photo": "https://drive.google.com/file/d/1GFM5eZnTYZ381lwQmbHbW5sfaB4j-o6R/view?usp=sharing",
              "Email_Id": "",
              "Status": "Not Sold"
            },
            {
              "Id": 97,
              "Player_Name": "Jasveen Nagda",
              "Mobile_Number": 9004688116,
              "Location": "Dombivli",
              "Village": "Bhojay",
              "NPL1_NPL2": "Both",
              "Cricket_Type": "Allrounder",
              "TShirt_Size": "",
              "Age": "",
              "Gender": "Male",
              "Payment_SS": "Committee",
              "Photo": "",
              "Email_Id": "",
              "Status": "Not Sold"
            },
            {
              "Id": 98,
              "Player_Name": "Kevin Praful Nagda",
              "Mobile_Number": 8169948960,
              "Location": "Mulund",
              "Village": "Kotdi Mahadevpuri",
              "NPL1_NPL2": "Both",
              "Cricket_Type": "Allrounder",
              "TShirt_Size": "L",
              "Age": 24,
              "Gender": "Male",
              "Payment_SS": "Paid",
              "Photo": "kevin.jpeg",
              "Email_Id": "",
              "Status": "Not Sold"
            },
            {
              "Id": 99,
              "Player_Name": "Chintan Rajesh Nagda",
              "Mobile_Number": 9773014397,
              "Location": "",
              "Village": "Makda",
              "NPL1_NPL2": "None",
              "Cricket_Type": "Allrounder",
              "TShirt_Size": "XXL",
              "Age": "",
              "Gender": "Male",
              "Payment_SS": "Paid",
              "Photo": "https://drive.google.com/file/d/1uesY_9_AU0pcx4PSl8HUGQxJPCQ-tDZx/view?usp=sharing",
              "Email_Id": "chintannagda1999@gmail.com",
              "Status": "Not Sold"
            },
            {
              "Id": 100,
              "Player_Name": "Vrutik Pravin Nagda",
              "Mobile_Number": 9699521325,
              "Location": "kalyan",
              "Village": "Naredi",
              "NPL1_NPL2": "NPL-2",
              "Cricket_Type": "Allrounder",
              "TShirt_Size": "Xxl",
              "Age": 22,
              "Gender": "Male",
              "Payment_SS": "https://drive.google.com/open?id=1nIV5S-h1Ch9GOVguaavEAf1-bu2-B82h",
              "Photo": "https://drive.google.com/open?id=1pvE3va8ZhzOqv_wQG_o0C3wpN7mwN_-_",
              "Email_Id": "Vrutiknagda23@gmail.com",
              "Status": "Not Sold"
            },
            {
              "Id": 101,
              "Player_Name": "Darshan Ketan Nagda",
              "Mobile_Number": 9930973666,
              "Location": "Vasai",
              "Village": "Dumra",
              "NPL1_NPL2": "None",
              "Cricket_Type": "Allrounder",
              "TShirt_Size": "M",
              "Age": 31,
              "Gender": "Male",
              "Payment_SS": "https://drive.google.com/open?id=1HU-FQySkEpOKU7ebxAhXYZf7rI1nVRrs",
              "Photo": "https://drive.google.com/open?id=1lQHIFWBpVlV7o8gBoAP_kx2Nnq05AXww",
              "Email_Id": "darshannagda1992@yahoo.com",
              "Status": "Not Sold"
            },
            {
              "Id": 102,
              "Player_Name": "Yash Jayesh Nagda",
              "Mobile_Number": 7738535508,
              "Location": "Mulund",
              "Village": "Naredi",
              "NPL1_NPL2": "None",
              "Cricket_Type": "Bowling",
              "TShirt_Size": "XL",
              "Age": 26,
              "Gender": "Male",
              "Payment_SS": "https://drive.google.com/open?id=1rp2rGwHN3Tvw2zWUM_v1B09c8DCFeMV2",
              "Photo": "https://drive.google.com/open?id=1O_NKM1gXu8JaP3YZruk755DWRZzMNK_6",
              "Email_Id": "babbunagda@gmail.com",
              "Status": "Not Sold"
            },
            {
              "Id": 103,
              "Player_Name": "Pankhil Deepesh Nagda",
              "Mobile_Number": 8591440332,
              "Location": "Ghatkopar",
              "Village": "Sanosara",
              "NPL1_NPL2": "None",
              "Cricket_Type": "Allrounder",
              "TShirt_Size": "L",
              "Age": 17,
              "Gender": "Male",
              "Payment_SS": "https://drive.google.com/open?id=1criyVK5CIYAOXSj8ujyU4ooIvg_6rmij",
              "Photo": "https://drive.google.com/open?id=1QzPswFN7YDSuo9ohUBe-EUGPGBqbesOu",
              "Email_Id": "pankhil.nagada@gmail.com",
              "Status": "Not Sold"
            },
            {
              "Id": 104,
              "Player_Name": "Kunjesh Raju Shah/ Nagda",
              "Mobile_Number": 9773550490,
              "Location": "Mulund",
              "Village": "Sanosara",
              "NPL1_NPL2": "None",
              "Cricket_Type": "Allrounder",
              "TShirt_Size": "M",
              "Age": 33,
              "Gender": "Male",
              "Payment_SS": "https://drive.google.com/open?id=1a3RRT3r3a2IW5fpl2BN5dSobqXO4ORyp",
              "Photo": "https://drive.google.com/open?id=1vCQFscwfpoNt77bbaA6d9PUSPLNtXhT0",
              "Email_Id": "kunjesh.90@gmail.com",
              "Status": "Not Sold"
            },
            {
              "Id": 105,
              "Player_Name": "Tirth Dewang Nagda",
              "Mobile_Number": 7715055918,
              "Location": "Ghatkopar",
              "Village": "Sanosara/bhuj",
              "NPL1_NPL2": "None",
              "Cricket_Type": "Bowling",
              "TShirt_Size": "M",
              "Age": 15,
              "Gender": "Male",
              "Payment_SS": "https://drive.google.com/open?id=19vx7VMsll-csUcybiDt2-MHnMBPN_Ecu",
              "Photo": "https://drive.google.com/open?id=1ss0BMyXGY8-AnHFMJ_Rs98iqomaDJBdb",
              "Email_Id": "No",
              "Status": "Not Sold"
            },
            {
              "Id": 106,
              "Player_Name": "Bhavya Mahendra Nagda",
              "Mobile_Number": 9987526605,
              "Location": "Mulund",
              "Village": "Sanosara",
              "NPL1_NPL2": "NPL-1",
              "Cricket_Type": "Batting",
              "TShirt_Size": "LARGE (L)",
              "Age": 18,
              "Gender": "Male",
              "Payment_SS": "https://drive.google.com/open?id=1zYKCdz68dNkpeOWqnOB3A0anJ4jNQpxu",
              "Photo": "https://drive.google.com/open?id=1EBqMtUo8w1a67M9HiXyDakbFopD8EwT4",
              "Email_Id": "bhavya05nagda@gmail.com",
              "Status": "Not Sold"
            },
            {
              "Id": 107,
              "Player_Name": "Bhagya Ramesh Nagda",
              "Mobile_Number": 9969591122,
              "Location": "Mulund",
              "Village": "Naredi",
              "NPL1_NPL2": "None",
              "Cricket_Type": "Bowling",
              "TShirt_Size": "M",
              "Age": 19,
              "Gender": "Male",
              "Payment_SS": "https://drive.google.com/open?id=1vKZmHmeJj0146ZHCiTq62LeYxCnjHVNr",
              "Photo": "https://drive.google.com/open?id=1G_dB79uHfHGJH4saj0k3FKQcm4YzYuFS",
              "Email_Id": "bhagyanagda01970@gmail.com",
              "Status": "Not Sold"
            },
            {
              "Id": 108,
              "Player_Name": "Khetan Nagda",
              "Mobile_Number": 9819574692,
              "Location": "Borivali east",
              "Village": "Kotda roha",
              "NPL1_NPL2": "None",
              "Cricket_Type": "Allrounder",
              "TShirt_Size": "XXL",
              "Age": 33,
              "Gender": "Male",
              "Payment_SS": "https://drive.google.com/open?id=1F8Mi8tJY7kiUWadDkTGuEp0dvzr-jDLx",
              "Photo": "https://drive.google.com/open?id=1FJ8kn-r3IbPvw-4k7_M2hmDf6ixhzehT",
              "Email_Id": "Khetan.nagda1990@gmail.com",
              "Status": "Not Sold"
            },
            {
              "Id": 109,
              "Player_Name": "Hiren Nanji Nagda",
              "Mobile_Number": 9869319350,
              "Location": "Wadala",
              "Village": "Sanosara",
              "NPL1_NPL2": "None",
              "Cricket_Type": "Allrounder",
              "TShirt_Size": "Xxl",
              "Age": 43,
              "Gender": "Male",
              "Payment_SS": "https://drive.google.com/open?id=1Z4nUoqDuSG3uiS0mDn7ZSMi4h74bQk-x",
              "Photo": "https://drive.google.com/open?id=17gz-UF8k-8NufK-JGkM55OcwQjS-o6bp",
              "Email_Id": "hirenngd@gmail.com",
              "Status": "Not Sold"
            },
            {
              "Id": 110,
              "Player_Name": "Kunaal dilip nagda",
              "Mobile_Number": 7972554561,
              "Location": "Vasai",
              "Village": "Naredi",
              "NPL1_NPL2": "None",
              "Cricket_Type": "Allrounder",
              "TShirt_Size": "XL",
              "Age": 38,
              "Gender": "Male",
              "Payment_SS": "https://drive.google.com/open?id=1psQDsA39qcuRirNjea1YwmWuf6pdtcig",
              "Photo": "https://drive.google.com/open?id=1cwwszAzop1OqGZHC2zb_koHYy8hYQLsX",
              "Email_Id": "kunaalnaagda@gmail.com",
              "Status": "Not Sold"
            },
            {
              "Id": 111,
              "Player_Name": "Jay sudhir nagda",
              "Mobile_Number": 8898880881,
              "Location": "Kandivali",
              "Village": "Bhinsara",
              "NPL1_NPL2": "NPL-2",
              "Cricket_Type": "Allrounder",
              "TShirt_Size": "Xxl",
              "Age": 30,
              "Gender": "Male",
              "Payment_SS": "https://drive.google.com/open?id=1rhC3BDhsN63N-9eEJzkww8q1CRYvdXC9",
              "Photo": "https://drive.google.com/open?id=18WsKhsH7Gfj9H6fd_3K0aE6_S_C1H0qd",
              "Email_Id": "deepsudhirshah@gmail.com",
              "Status": "Not Sold"
            },
            {
              "Id": 112,
              "Player_Name": "Saumya Hemant Nagda",
              "Mobile_Number": 8169433849,
              "Location": "Dombivali",
              "Village": "Bhojay",
              "NPL1_NPL2": "NPL-2",
              "Cricket_Type": "Batting",
              "TShirt_Size": "M",
              "Age": 17,
              "Gender": "Male",
              "Payment_SS": "https://drive.google.com/open?id=1UR7IZg3mo89IBJTXOo4wVOs1b3PgB_lE",
              "Photo": "https://drive.google.com/open?id=1bXU3kK4H-VxG9nQpRszPrA6MWWdCtGJl",
              "Email_Id": "saumyanagda098@gmail.com",
              "Status": "Not Sold"
            },
            {
              "Id": 113,
              "Player_Name": "Harsh Jayesh Nagda",
              "Mobile_Number": 9773528812,
              "Location": "Malad",
              "Village": "Bhojay",
              "NPL1_NPL2": "Both",
              "Cricket_Type": "Allrounder",
              "TShirt_Size": "M",
              "Age": 24,
              "Gender": "Male",
              "Payment_SS": "https://drive.google.com/open?id=17bfiT2SGuT9XEBcMhR_vLfkq4fwJdXnE",
              "Photo": "https://drive.google.com/open?id=1P7iA6LBteG8WcW9gX3eNBR9FFwbj3lV6",
              "Email_Id": "nagdaharsh43@gmail.com",
              "Status": "Not Sold"
            },
            {
              "Id": 114,
              "Player_Name": "Mahek Nagda",
              "Mobile_Number": 7303958780,
              "Location": "Vasai",
              "Village": "Bhojay",
              "NPL1_NPL2": "Both",
              "Cricket_Type": "Batting",
              "TShirt_Size": "L",
              "Age": 24,
              "Gender": "Male",
              "Payment_SS": "https://drive.google.com/open?id=12Ue9Gc4lNaZt1Vc43iKbrontOYb0dYwv",
              "Photo": "https://drive.google.com/open?id=1e3I1xbQ8nx5XF2uH1zhiQabX6r1RW7oX",
              "Email_Id": "nagda.mahek2@gmail.com",
              "Status": "Not Sold"
            },
            {
              "Id": 115,
              "Player_Name": "Jenil Dinesh Nagda",
              "Mobile_Number": 9326774994,
              "Location": "Dombivli",
              "Village": "Moti-Undoth",
              "NPL1_NPL2": "Both",
              "Cricket_Type": "Allrounder",
              "TShirt_Size": "L",
              "Age": 25,
              "Gender": "Male",
              "Payment_SS": "https://drive.google.com/open?id=1uVkZKyEZSnVyZDndGiHLVDf_dB8YKnXl",
              "Photo": "https://drive.google.com/open?id=1NM-SPFbgVnJh0g3x0NZgXmTx0Qf4bqGp",
              "Email_Id": "jenilnagda9@gmail.com",
              "Status": "Not Sold"
            },
            {
              "Id": 116,
              "Player_Name": "Mulchand Dhanji Nagda",
              "Mobile_Number": 8689861502,
              "Location": "Dombivli",
              "Village": "Kotda Roha",
              "NPL1_NPL2": "None",
              "Cricket_Type": "Allrounder",
              "TShirt_Size": "M",
              "Age": 48,
              "Gender": "Male",
              "Payment_SS": "https://drive.google.com/open?id=1kSlQT7V1Xb2ujJvg75Ww-p58PjdHUO0e",
              "Photo": "https://drive.google.com/open?id=1vzOt_nTo4LyaFj9XgQSWADAlfdYAcfrX",
              "Email_Id": "tusmit.shah@somaiya.edu",
              "Status": "Not Sold"
            },
            {
              "Id": 117,
              "Player_Name": "Krish jasveen nagda",
              "Mobile_Number": 9867158589,
              "Location": "Dombivli",
              "Village": "Bhojay",
              "NPL1_NPL2": "Both",
              "Cricket_Type": "Allrounder",
              "TShirt_Size": "L",
              "Age": 15,
              "Gender": "Male",
              "Payment_SS": "https://drive.google.com/open?id=1v784ygYgTcfchJWD4pdTaYgbOdUAAkTF",
              "Photo": "https://drive.google.com/open?id=18IiwGkmzW1B7gzbj6gnEmt3xVKbSbXEA",
              "Email_Id": "jaseen.nagda1983@gmail.com",
              "Status": "Not Sold"
            },
            {
              "Id": 118,
              "Player_Name": "Hiren Vasant Shah /Nagda",
              "Mobile_Number": 9321020846,
              "Location": "Sion",
              "Village": "Koday",
              "NPL1_NPL2": "NPL-2",
              "Cricket_Type": "Allrounder",
              "TShirt_Size": "XL",
              "Age": 46,
              "Gender": "Male",
              "Payment_SS": "https://drive.google.com/open?id=16T0-Nh3qzHRJb6ESqkUImtvE2J3Tj2xH",
              "Photo": "https://drive.google.com/open?id=1sASPbCOIxnXwYzhpMBE6B8L9wuykUPj0",
              "Email_Id": "hiren20846@gmail.com",
              "Status": "Not Sold"
            },
            {
              "Id": 119,
              "Player_Name": "Aayush Akshay Nagda",
              "Mobile_Number": 9821039990,
              "Location": "BORIVALI",
              "Village": "NAREDI",
              "NPL1_NPL2": "None",
              "Cricket_Type": "Batting",
              "TShirt_Size": "L",
              "Age": 25,
              "Gender": "Male",
              "Payment_SS": "https://drive.google.com/open?id=1ctC5hHgzdCU-2mMvBU-fUX_OwBzNciQY",
              "Photo": "https://drive.google.com/open?id=1GTl1LZXiyR8yCeDOFwNKGpp__yPa6uYm",
              "Email_Id": "nagda.aayush@gmail.com",
              "Status": "Not Sold"
            },
            {
              "Id": 120,
              "Player_Name": "JAYESH VALLABHJI NAGDA",
              "Mobile_Number": 9967090995,
              "Location": "Mulund checknaka",
              "Village": "Sabharai",
              "NPL1_NPL2": "Both",
              "Cricket_Type": "Allrounder",
              "TShirt_Size": "XXL",
              "Age": 47,
              "Gender": "Male",
              "Payment_SS": "https://drive.google.com/open?id=1VfWMQ14mkP3F5WCMWPNmmOLi9QX63Y_0",
              "Photo": "https://drive.google.com/open?id=1cGmt7oKHYiQSVYt-KF_yiu_tlXeUgslT",
              "Email_Id": "cajayeshnagda@gmail.com",
              "Status": "Not Sold"
            },
            {
              "Id": 121,
              "Player_Name": "KAVAN JAYESH NAGDA",
              "Mobile_Number": 8928114461,
              "Location": "MULUND CHECKNAKA THANE",
              "Village": "SABHARAI",
              "NPL1_NPL2": "NPL-1",
              "Cricket_Type": "Allrounder",
              "TShirt_Size": "XL",
              "Age": 15.5,
              "Gender": "Male",
              "Payment_SS": "https://drive.google.com/open?id=14CGSPzaJoA_vp7pHj6eEmDpq1EB4cpWp",
              "Photo": "https://drive.google.com/open?id=18usB9co5kRI9vphF4Fmgz81TS78T8wD5",
              "Email_Id": "kavanjayeshnagda@gmail.com",
              "Status": "Not Sold"
            },
            {
              "Id": 122,
              "Player_Name": "Jiten Gangji Nagda",
              "Mobile_Number": 9867868060,
              "Location": "Thane",
              "Village": "Moti Undoth",
              "NPL1_NPL2": "None",
              "Cricket_Type": "Allrounder",
              "TShirt_Size": "XL",
              "Age": 40,
              "Gender": "Male",
              "Payment_SS": "https://drive.google.com/open?id=188rDYLs8_KEuVr6CWNe4xQFdkeni16gB",
              "Photo": "https://drive.google.com/open?id=1CM9ucNbafqDsbN6kFzOjevtpSCPhgk_4",
              "Email_Id": "NA",
              "Status": "Not Sold"
            },
            {
              "Id": 123,
              "Player_Name": "Ritesh mohan Nagda",
              "Mobile_Number": 9137101315,
              "Location": "Dombivali",
              "Village": "Vidh",
              "NPL1_NPL2": "None",
              "Cricket_Type": "Allrounder",
              "TShirt_Size": "XL",
              "Age": 23,
              "Gender": "Male",
              "Payment_SS": "https://drive.google.com/open?id=1Fwaq6Jpb2WYNIVtuedK61PgV9g3yYWM2",
              "Photo": "https://drive.google.com/open?id=1I4_f3mzAYtSN15UxdGJd7z_uZQ8nm9XP",
              "Email_Id": "Riteshmnagda@gmail.com",
              "Status": "Not Sold"
            },
            {
              "Id": 124,
              "Player_Name": "Deep sudhir nagda",
              "Mobile_Number": 9821313321,
              "Location": "Kandivali",
              "Village": "Bhinsara",
              "NPL1_NPL2": "None",
              "Cricket_Type": "Allrounder",
              "TShirt_Size": "Xl",
              "Age": 28,
              "Gender": "Male",
              "Payment_SS": "https://drive.google.com/open?id=1aRchBKSqvGngMDNZAn2rc7FDL9Bq4z0B",
              "Photo": "https://drive.google.com/open?id=142v8YGuhseWrHB_FOyW-RlKa6wrsyJQ-",
              "Email_Id": "deepsudhirshah@gmail.com",
              "Status": "Not Sold"
            },
            {
              "Id": 125,
              "Player_Name": "Ankit Bhailal Nagda",
              "Mobile_Number": 9975231621,
              "Location": "Vasai",
              "Village": "Sanosara",
              "NPL1_NPL2": "Both",
              "Cricket_Type": "Allrounder",
              "TShirt_Size": "M",
              "Age": 37,
              "Gender": "Male",
              "Payment_SS": "https://drive.google.com/open?id=1kLIJcNwRgl9ecYSq_BYdV0BZQhmtGkOT",
              "Photo": "https://drive.google.com/open?id=1LKH-ZRogCzpSjQGq_-cTl76M-xFV_vhC",
              "Email_Id": "ankit.nagada@gmail.com",
              "Status": "Not Sold"
            },
            {
              "Id": 126,
              "Player_Name": "Chintan Haresh Nagda",
              "Mobile_Number": 9619715444,
              "Location": "Dombivli",
              "Village": "Naredi",
              "NPL1_NPL2": "None",
              "Cricket_Type": "Batting",
              "TShirt_Size": "S",
              "Age": 23,
              "Gender": "Male",
              "Payment_SS": "https://drive.google.com/open?id=1imH45PuygT8_iNkh-5vUEhH8c3pNy8lg",
              "Photo": "https://drive.google.com/open?id=1sDKjS-shRdxo7dvC9za9-ff4mkgIrX85",
              "Email_Id": "nagdachintan267@gmail.com",
              "Status": "Not Sold"
            }
          ];
   }
}