export const MaleData = {
    getMaleData : function() {
        return [
          {
            "Id": 1,
            "Player_Name": "Rahul Devchand Nagda",
            "Mobile_Number": 9022720865,
            "Location": "Malad",
            "Village": "Vindh",
            "NPL1_NPL2": "None",
            "Cricket_Type": "Allrounder",
            "TShirt_Size": "M",
            "Age": 30,
            "Gender": "Male",
            "Payment_SS": "https://drive.google.com/open?id=1lhGMsiZj5SZ9As_9HLDIdzw8a8WXxm7W",
            "Photo": "https://drive.google.com/open?id=1HABF_rpyfUWdXwcZ4Rnt7oESzCEw4s2I"
          },
          {
            "Id": 2,
            "Player_Name": "Amit Suresh nagda",
            "Mobile_Number": 9892931665,
            "Location": "Dahisar",
            "Village": "Bhojay",
            "NPL1_NPL2": "None",
            "Cricket_Type": "Allrounder",
            "TShirt_Size": "XL",
            "Age": 41,
            "Gender": "Male",
            "Payment_SS": "https://drive.google.com/open?id=1TaI-StT9Fm8Ihgg8igjvtAxWWJIYuRkF",
            "Photo": "https://drive.google.com/open?id=1QSAdIUBbibCDuBHd0q6CIllJzUuFWgAe"
          },
          {
            "Id": 3,
            "Player_Name": "Sanyam Gautam Shah/Nagda",
            "Mobile_Number": 7020890757,
            "Location": "Virar",
            "Village": "Naredi",
            "NPL1_NPL2": "NPL-2",
            "Cricket_Type": "Allrounder",
            "TShirt_Size": "L",
            "Age": 20,
            "Gender": "Male",
            "Payment_SS": "https://drive.google.com/open?id=1NGEXynG-1eu3MAFAClJpa3BNOGUHRkZa",
            "Photo": "https://drive.google.com/open?id=1D-AqmnCK1nfhC5VUNQGiQBOBzLeneg8e"
          },
          {
            "Id": 4,
            "Player_Name": "Hardik Kishor Nagda",
            "Mobile_Number": 7709181594,
            "Location": "Mumbai",
            "Village": "Sanosara",
            "NPL1_NPL2": "NPL-1",
            "Cricket_Type": "Allrounder",
            "TShirt_Size": "M",
            "Age": 33,
            "Gender": "Male",
            "Payment_SS": "https://drive.google.com/open?id=1Svamr7kj5k8ZplrEvzacWQLrYMhXCCxu",
            "Photo": "https://drive.google.com/open?id=1fuFp9K0D4B3uw_miytPiGG2PacLPPu8k"
          },
          {
            "Id": 5,
            "Player_Name": "Chirag damji nagda",
            "Mobile_Number": 9821392929,
            "Location": "Mulund east",
            "Village": "Naredi",
            "NPL1_NPL2": "NPL-2",
            "Cricket_Type": "Batting",
            "TShirt_Size": "Xl",
            "Age": 38,
            "Gender": "Male",
            "Payment_SS": "https://drive.google.com/open?id=1RMYyYx8UUPqvfo5kcELIioGfy0139074",
            "Photo": "https://drive.google.com/open?id=1oOF70w55CgbL7TaIKENqpYgrE1E5kmfv"
          },
          {
            "Id": 6,
            "Player_Name": "Chirag Rakesh Shah / Nagda",
            "Mobile_Number": 7738837875,
            "Location": "Kalyan",
            "Village": "Vidh",
            "NPL1_NPL2": "NPL-2",
            "Cricket_Type": "Allrounder",
            "TShirt_Size": "XL",
            "Age": 20,
            "Gender": "Male",
            "Payment_SS": "https://drive.google.com/open?id=1k4GOPCFJpjA_bZyAQw00y5B3iTO8fjES",
            "Photo": "https://drive.google.com/open?id=12rbz_pFgFzboUcL8MzWkra5ky2bNW2tD"
          },
          {
            "Id": 7,
            "Player_Name": "Akshit Rajesh nagda",
            "Mobile_Number": 8956795831,
            "Location": "Ambernath",
            "Village": "Kotdi Mahadev puri",
            "NPL1_NPL2": "NPL-2",
            "Cricket_Type": "Allrounder",
            "TShirt_Size": "Xxl",
            "Age": 21,
            "Gender": "Male",
            "Payment_SS": "https://drive.google.com/open?id=1zFdFaU_wewd1lUiqn27j34IPxG6c8kSV",
            "Photo": "https://drive.google.com/open?id=1AmZJYihHXMsaw_mXGgAfTVWO2IFErPkb"
          },
          {
            "Id": 8,
            "Player_Name": "JIGAR PRAKASH SHAH/NAGDA",
            "Mobile_Number": 9022645274,
            "Location": "Byculla",
            "Village": "Bhisra",
            "NPL1_NPL2": "NPL-1",
            "Cricket_Type": "Allrounder",
            "TShirt_Size": "5XL",
            "Age": 30,
            "Gender": "Male",
            "Payment_SS": "https://drive.google.com/open?id=1_pPRmFQDv6aLwktRhQJ8OeZpxtm3Zy25",
            "Photo": "https://drive.google.com/open?id=1EzVAPB-n_OxYhDEGCbAQ2e4TVXSJSxh3"
          },
          {
            "Id": 9,
            "Player_Name": "Kalpesh Damji Nagda",
            "Mobile_Number": 9819706426,
            "Location": "Thana",
            "Village": "Sanosara",
            "NPL1_NPL2": "Both",
            "Cricket_Type": "Allrounder",
            "TShirt_Size": "M",
            "Age": 45,
            "Gender": "Male",
            "Payment_SS": "https://drive.google.com/open?id=1vvH5QP1nwVLYcaip4q5Az-vNBIj5kwpw",
            "Photo": "https://drive.google.com/open?id=1sw2N5eJuSytg21gNubUE7sSX_Y5jWUuP"
          },
          {
            "Id": 10,
            "Player_Name": "Chunmay Gautam Shah/Nagda",
            "Mobile_Number": 9307388951,
            "Location": "Virar",
            "Village": "Naredi",
            "NPL1_NPL2": "NPL-2",
            "Cricket_Type": "Allrounder",
            "TShirt_Size": "L",
            "Age": 17,
            "Gender": "Male",
            "Payment_SS": "https://drive.google.com/open?id=1EdpVIxngnYuu09HjQRCXvHi7uGEGqjxF",
            "Photo": "https://drive.google.com/open?id=1EzcGtTZQHkuOlXHe69UBG9EM1BYXwieZ"
          },
          {
            "Id": 11,
            "Player_Name": "Mahesh Damji Shah",
            "Mobile_Number": 9867431637,
            "Location": "Bhandup West",
            "Village": "Sanosara",
            "NPL1_NPL2": "NPL-2",
            "Cricket_Type": "Allrounder",
            "TShirt_Size": "M",
            "Age": 46,
            "Gender": "Male",
            "Payment_SS": "https://drive.google.com/open?id=1LnRAE5HtsgKcQUxNnMmQX0q_bkspr0Qm",
            "Photo": "https://drive.google.com/open?id=1SuHVj3TlCRLiTxpQqH8PrbZS8hE0CjCR"
          },
          {
            "Id": 12,
            "Player_Name": "Mihir Jayantilal Nagda",
            "Mobile_Number": 9664875667,
            "Location": "Virar west",
            "Village": "Sanosara",
            "NPL1_NPL2": "None",
            "Cricket_Type": "Bowling",
            "TShirt_Size": "XXXL",
            "Age": 32,
            "Gender": "Male",
            "Payment_SS": "https://drive.google.com/open?id=1CN9Y50M_yfLPLxahENkVpVbGjNJrPyTq",
            "Photo": "https://drive.google.com/open?id=1_Z-ei6jaz-51mGmatknhrbK3CCJZhRiW"
          },
          {
            "Id": 13,
            "Player_Name": "Ramesh Nagda",
            "Mobile_Number": 8108051007,
            "Location": "Mulund",
            "Village": "Naredi",
            "NPL1_NPL2": "Both",
            "Cricket_Type": "Bowling",
            "TShirt_Size": "XL",
            "Age": 46,
            "Gender": "Male",
            "Payment_SS": "https://drive.google.com/open?id=1_fGA_B38MT_-UcvDO3suXtXZNF4fkYPW",
            "Photo": "https://drive.google.com/open?id=11gM6vtsbFPRkqX2zEL1hpxDcDOHvxgpV"
          },
          {
            "Id": 14,
            "Player_Name": "Harsh Bipin Nagda",
            "Mobile_Number": 7738622896,
            "Location": "Nallasopara",
            "Village": "Godhra",
            "NPL1_NPL2": "Both",
            "Cricket_Type": "Allrounder",
            "TShirt_Size": "XXL",
            "Age": 30,
            "Gender": "Male",
            "Payment_SS": "https://drive.google.com/open?id=1KIRFrQbJAYH_ROtVxWAYhbZLQoEKxRwW",
            "Photo": "https://drive.google.com/open?id=1TE6kAeLCWraJ1-krpHlm8IXphXp2syHK"
          },
          {
            "Id": 15,
            "Player_Name": "Chintan Virendra Nagda",
            "Mobile_Number": 9503164649,
            "Location": "Nallasopara",
            "Village": "Changdai",
            "NPL1_NPL2": "Both",
            "Cricket_Type": "Allrounder",
            "TShirt_Size": "L",
            "Age": 25,
            "Gender": "Male",
            "Payment_SS": "https://drive.google.com/open?id=1tWosVDCGAGq41sFnoO8I2LpaPIDaWu89",
            "Photo": "https://drive.google.com/open?id=1yXvvNH0-VlRFeVQKa-qr1Mi5k4GDYJqe"
          },
          {
            "Id": 16,
            "Player_Name": "VAIBHAV NARESH NAGDA",
            "Mobile_Number": 9969540404,
            "Location": "BHANDUP",
            "Village": "DUMRA",
            "NPL1_NPL2": "NPL-2",
            "Cricket_Type": "Allrounder",
            "TShirt_Size": "XL",
            "Age": 31,
            "Gender": "Male",
            "Payment_SS": "https://drive.google.com/open?id=1FtuCMF_3TNbIbvtWM4v42a0ipwJ6XMrO",
            "Photo": "https://drive.google.com/open?id=1RbKINMcLy9aKG8u6gBOqtWMH-3RHdzcZ"
          },
          {
            "Id": 17,
            "Player_Name": "Mehul P Shah / Nagda",
            "Mobile_Number": 9920679681,
            "Location": "Mulund",
            "Village": "Sanosara",
            "NPL1_NPL2": "Both",
            "Cricket_Type": "Allrounder",
            "TShirt_Size": "L",
            "Age": 44,
            "Gender": "Male",
            "Payment_SS": "https://drive.google.com/open?id=1ILJTRYqXK7z6UeUbQYkB8T9RxtGeNzW5",
            "Photo": "https://drive.google.com/open?id=1vCC00sFCQsgzJJ6wWDLfYl4lk_FhkS4W"
          },
          {
            "Id": 18,
            "Player_Name": "Mehul suresh nagda",
            "Mobile_Number": 9821182188,
            "Location": "Dahisar",
            "Village": "Bhojay",
            "NPL1_NPL2": "None",
            "Cricket_Type": "Batting",
            "TShirt_Size": "XXL",
            "Age": 39,
            "Gender": "Male",
            "Payment_SS": "https://drive.google.com/open?id=1mNMr8YhYVnisNzZ4Slq4vzj2whJ_bxiv",
            "Photo": "https://drive.google.com/open?id=1RtDW_B4bi08V18yAehVwgxrQcKdvR92L"
          },
          {
            "Id": 19,
            "Player_Name": "Keval Vallabhji Nagda",
            "Mobile_Number": 9096789096,
            "Location": "Mumbai",
            "Village": "Sanosara",
            "NPL1_NPL2": "None",
            "Cricket_Type": "Allrounder",
            "TShirt_Size": "XXL",
            "Age": 31,
            "Gender": "Male",
            "Payment_SS": "https://drive.google.com/open?id=1mYdHLyyB2OzlgdL9Q0nW7o_t38bXiZ-X",
            "Photo": "https://drive.google.com/open?id=1Z212L9xRS6nkenv3VXESoR7YUTbJJUDz"
          },
          {
            "Id": 20,
            "Player_Name": "Rushabh Nagda",
            "Mobile_Number": 8082494675,
            "Location": "Dombivli",
            "Village": "Vidh",
            "NPL1_NPL2": "Both",
            "Cricket_Type": "Batting",
            "TShirt_Size": "L",
            "Age": 30,
            "Gender": "Male",
            "Payment_SS": "https://drive.google.com/open?id=14VEnFhH841mOEalhvkHLkYm4khGN3CVc",
            "Photo": "https://drive.google.com/open?id=1lbOW7lii0y_-OCgrWH45K5FiLWiJV3Ep"
          },
          {
            "Id": 21,
            "Player_Name": "Parth Harakchand Nagda",
            "Mobile_Number": 8082053932,
            "Location": "Mulund",
            "Village": "Vindh",
            "NPL1_NPL2": "NPL-2",
            "Cricket_Type": "Allrounder",
            "TShirt_Size": "L",
            "Age": 28,
            "Gender": "Male",
            "Payment_SS": "https://drive.google.com/open?id=1ChH8dATBcfZZzj3Pi1iy3Lea8vDTn7cv",
            "Photo": "https://drive.google.com/open?id=1as3o_f3GeaKjqDE7csuYnM3a1tj8lXMX"
          },
          {
            "Id": 22,
            "Player_Name": "Lokesh Nagda",
            "Mobile_Number": 7666991833,
            "Location": "Dombivali",
            "Village": "Vidh",
            "NPL1_NPL2": "NPL-2",
            "Cricket_Type": "Batting",
            "TShirt_Size": "Xl",
            "Age": 34,
            "Gender": "Male",
            "Payment_SS": "https://drive.google.com/open?id=1IerOcvQmct8d9fXmbC85qBRa4nvsdVsh",
            "Photo": "https://drive.google.com/open?id=1sUiiv2oLz2EU4eGkbW7Ic6zb9rlz1YgC"
          },
          {
            "Id": 23,
            "Player_Name": "Hardik Harakchand Nagda",
            "Mobile_Number": 9821684526,
            "Location": "Mulund",
            "Village": "Vidh",
            "NPL1_NPL2": "NPL-2",
            "Cricket_Type": "Allrounder",
            "TShirt_Size": "L",
            "Age": 33,
            "Gender": "Male",
            "Payment_SS": "https://drive.google.com/open?id=1Q2g5N2XU24rghWeGpsNzMpNWNSP217g6",
            "Photo": "https://drive.google.com/open?id=1H8V1ezPndqkHWVil7fExl85z17qzCxm0"
          },
          {
            "Id": 24,
            "Player_Name": "Jeet Naresh Nagda",
            "Mobile_Number": 9969752621,
            "Location": "Bhandup",
            "Village": "Dumra",
            "NPL1_NPL2": "NPL-2",
            "Cricket_Type": "Allrounder",
            "TShirt_Size": "XL",
            "Age": 28,
            "Gender": "Male",
            "Payment_SS": "https://drive.google.com/open?id=1MmeLMolA93hwxnPZ3d5jnzsmA6HW2kE4",
            "Photo": "https://drive.google.com/open?id=1tHTINvrqOpTyMEvcgkCHIZZzBceQLSm5"
          },
          {
            "Id": 25,
            "Player_Name": "Rohan Devendra shah / Nagda",
            "Mobile_Number": 9833592828,
            "Location": "MAZGAON",
            "Village": "Bhinsara",
            "NPL1_NPL2": "NPL-1",
            "Cricket_Type": "Allrounder",
            "TShirt_Size": "L",
            "Age": 36,
            "Gender": "Male",
            "Payment_SS": "https://drive.google.com/open?id=11iIqdFk4sqmOowl5pW1KxI45sq_yXrWx",
            "Photo": "https://drive.google.com/open?id=1CrGU1TKf4xbVlhUP09rwXYwXgs4hGxWR"
          },
          {
            "Id": 26,
            "Player_Name": "Shasan Kirti Nagda",
            "Mobile_Number": 9960411881,
            "Location": "VASAI",
            "Village": "Naredi",
            "NPL1_NPL2": "None",
            "Cricket_Type": "Allrounder",
            "TShirt_Size": "Xxl",
            "Age": 24,
            "Gender": "Male",
            "Payment_SS": "https://drive.google.com/open?id=1LCgp2x7h_n8plROrP4MfqMO1sUuyUrHT",
            "Photo": "https://drive.google.com/open?id=1Q9o98_8EH6Ql6G0tyDQTdV-vTMhb1uo_"
          },
          {
            "Id": 27,
            "Player_Name": "Khamir Chhaganlal Shah/Nagda",
            "Mobile_Number": 9920893389,
            "Location": "Chembur",
            "Village": "Bhinsara",
            "NPL1_NPL2": "NPL-1",
            "Cricket_Type": "Allrounder",
            "TShirt_Size": "XL",
            "Age": 45,
            "Gender": "Male",
            "Payment_SS": "https://drive.google.com/open?id=1T7biwPKvny8loRrKplIaa85oixu2eH-j",
            "Photo": "https://drive.google.com/open?id=1otOIXsxO1OPGSC3W0rwSa3h2bMQrnDHD"
          },
          {
            "Id": 28,
            "Player_Name": "Aaryan Ketan Nagda",
            "Mobile_Number": 8799249092,
            "Location": "Thane",
            "Village": "Sanosara",
            "NPL1_NPL2": "Both",
            "Cricket_Type": "Batting",
            "TShirt_Size": "Xxl",
            "Age": 20,
            "Gender": "Male",
            "Payment_SS": "https://drive.google.com/open?id=1em0DbWmtf5PFxATrU_Aav2aNckoSb-pb",
            "Photo": "https://drive.google.com/open?id=1Liqar1RoxSJYv5S2z2etJiIqcapC_w9i"
          },
          {
            "Id": 29,
            "Player_Name": "Jay Rajesh Nagda",
            "Mobile_Number": 9323125077,
            "Location": "Sanpada",
            "Village": "Sanosara",
            "NPL1_NPL2": "NPL-2",
            "Cricket_Type": "Allrounder",
            "TShirt_Size": "M",
            "Age": 18,
            "Gender": "Male",
            "Payment_SS": "https://drive.google.com/open?id=16yl3zP6gsn2HUBv_nRI-F1mxiTtRtTSW",
            "Photo": "https://drive.google.com/open?id=1wK5HvQAo5WZTLsf5ur0YvmgKfEbJjQKU"
          },
          {
            "Id": 30,
            "Player_Name": "Dhruv Vinesh Nagda",
            "Mobile_Number": 8356046150,
            "Location": "Mulund",
            "Village": "Sanosara",
            "NPL1_NPL2": "NPL-2",
            "Cricket_Type": "Allrounder",
            "TShirt_Size": "M",
            "Age": 18,
            "Gender": "Male",
            "Payment_SS": "https://drive.google.com/open?id=16RpsbVbGIJd-7JhTQFoxn7GSV1sy81vg",
            "Photo": "https://drive.google.com/open?id=1_aDL4igfbZ0laMk34EhLujeC3qtdJXUH"
          },
          {
            "Id": 31,
            "Player_Name": "Paras hiralal shah/ nagda",
            "Mobile_Number": 9324928147,
            "Location": "Ambernath",
            "Village": "Naredi",
            "NPL1_NPL2": "None",
            "Cricket_Type": "Allrounder",
            "TShirt_Size": "XXL",
            "Age": 44,
            "Gender": "Male",
            "Payment_SS": "https://drive.google.com/open?id=1hgyv_DP7nts7_PRnj_m-qnFl8v_R3tlX",
            "Photo": "https://drive.google.com/open?id=1_g7_JsKksufcp2B7Zx7sY6Oy-4-wGq_1"
          },
          {
            "Id": 32,
            "Player_Name": "Urvil Deepak Nagda",
            "Mobile_Number": 7039509323,
            "Location": "Kalwa",
            "Village": "Moti Undoth",
            "NPL1_NPL2": "NPL-2",
            "Cricket_Type": "Allrounder",
            "TShirt_Size": "L",
            "Age": 22,
            "Gender": "Male",
            "Payment_SS": "https://drive.google.com/open?id=1CaMpc2AQ862-bppFy1K9vG1LfCMVt6-3",
            "Photo": "https://drive.google.com/open?id=1--ZfiAK2l94lBBGm0gDdDVT0ubbv88uV"
          },
          {
            "Id": 33,
            "Player_Name": "Bhavesh Rasik Nagda",
            "Mobile_Number": 9987407527,
            "Location": "Vashi",
            "Village": "Changdai",
            "NPL1_NPL2": "NPL-1",
            "Cricket_Type": "Allrounder",
            "TShirt_Size": "M",
            "Age": 37,
            "Gender": "Male",
            "Payment_SS": "https://drive.google.com/open?id=1o-jfc3H6ufEH-MP7PXZFoCvcGN0YB2DJ",
            "Photo": "https://drive.google.com/open?id=1mjfwMybtmodarEU_NVA3R4J3F1mRSvyP"
          },
          {
            "Id": 34,
            "Player_Name": "Harshal Girish Nagda",
            "Mobile_Number": 9029370343,
            "Location": "Nalasopara",
            "Village": "Bhojay",
            "NPL1_NPL2": "None",
            "Cricket_Type": "Allrounder",
            "TShirt_Size": "M",
            "Age": 18,
            "Gender": "Male",
            "Payment_SS": "https://drive.google.com/open?id=1O1mhVqkY2nW5zKWzkVcUG7CSBQ9Z5WKl",
            "Photo": "https://drive.google.com/open?id=1eO3FJGzewYrx-zBJ1QRIGLz8aIZ18kpl"
          },
          {
            "Id": 35,
            "Player_Name": "Naman Lalit Jain",
            "Mobile_Number": 7620806592,
            "Location": "Ambernath",
            "Village": "Chanagdai",
            "NPL1_NPL2": "NPL-2",
            "Cricket_Type": "Allrounder",
            "TShirt_Size": "XL",
            "Age": 23,
            "Gender": "Male",
            "Payment_SS": "https://drive.google.com/open?id=1tRBV6pm2G6prhnamRsb2-5ZqoVUtDxnJ",
            "Photo": "https://drive.google.com/open?id=1C31R66luxZp3SvN0aoIZqgBUKD5tFolN"
          },
          {
            "Id": 36,
            "Player_Name": "Hitendra devraj Nagda",
            "Mobile_Number": 9920228841,
            "Location": "Dombivli",
            "Village": "Sanosara",
            "NPL1_NPL2": "NPL-2",
            "Cricket_Type": "Allrounder",
            "TShirt_Size": "Xxl",
            "Age": 45,
            "Gender": "Male",
            "Payment_SS": "https://drive.google.com/open?id=1BplyRiltDP5Pxgq1BnikyOJZmLSObHmk",
            "Photo": "https://drive.google.com/open?id=1nmnRCUOmnuU0FR3ftinhMPzGG8G61iTf"
          },
          {
            "Id": 37,
            "Player_Name": "Anil Jayantilal Nagda",
            "Mobile_Number": 9820171414,
            "Location": "Tardeo",
            "Village": "Kotdi Mahadevpuri",
            "NPL1_NPL2": "Both",
            "Cricket_Type": "Bowling",
            "TShirt_Size": "L",
            "Age": 46,
            "Gender": "Male",
            "Payment_SS": "https://drive.google.com/open?id=1ckdd2OOZYv8vGYAua0ViKEtLOpzVFeIo",
            "Photo": "https://drive.google.com/open?id=1XFRZRWcAVxHY-0rJpAuBINE7tHqUNmK4"
          },
          {
            "Id": 38,
            "Player_Name": "Param Piyush Nagda",
            "Mobile_Number": 9702223335,
            "Location": "Goregaon",
            "Village": "Sanosara",
            "NPL1_NPL2": "None",
            "Cricket_Type": "Allrounder",
            "TShirt_Size": "Xxl",
            "Age": 23,
            "Gender": "Male",
            "Payment_SS": "https://drive.google.com/open?id=1UjChkPA_lX2Cw4jPjO4tnvRjabYBb-wx",
            "Photo": "https://drive.google.com/open?id=1kT4rmKZFcRWmTKUB5Q-ojo1yM52-DMoW"
          },
          {
            "Id": 39,
            "Player_Name": "Bhavin Hiralal Nagda",
            "Mobile_Number": 9594040648,
            "Location": "Bhayandar west",
            "Village": "Moti Undoth",
            "NPL1_NPL2": "NPL-2",
            "Cricket_Type": "Allrounder",
            "TShirt_Size": "XL",
            "Age": 38,
            "Gender": "Male",
            "Payment_SS": "https://drive.google.com/open?id=1G0NwjUvVNFmqBsMmvMiUFVzxNuvY1zNv",
            "Photo": "https://drive.google.com/open?id=1-TfIp_lY9AGgu4a2bgsgCOp-q4305bBJ"
          },
          {
            "Id": 40,
            "Player_Name": "Rohan praful nagda",
            "Mobile_Number": 9819437111,
            "Location": "Thane",
            "Village": "Kotdi mahadevpuri",
            "NPL1_NPL2": "NPL-2",
            "Cricket_Type": "Batting",
            "TShirt_Size": "XXXL",
            "Age": 36,
            "Gender": "Male",
            "Payment_SS": "https://drive.google.com/open?id=1rKyi-HSigHULIPPSF8Crj3qwA4kFSESg",
            "Photo": "https://drive.google.com/open?id=1DLZwJuXMoCO35KatuS47I7zxpYFvd0yC"
          },
          {
            "Id": 41,
            "Player_Name": "Rushabh Navin Nagda",
            "Mobile_Number": 9323232000,
            "Location": "Juhu",
            "Village": "Changdai",
            "NPL1_NPL2": "Both",
            "Cricket_Type": "Batting",
            "TShirt_Size": "L",
            "Age": 23,
            "Gender": "Male",
            "Payment_SS": "https://drive.google.com/open?id=1isVhC5lHGT9Y9QJ6Ty0XeAcjkgw6p04t",
            "Photo": "https://drive.google.com/open?id=116wANPhXSbTHocTF-SFYRVGfL867fRBb"
          },
          {
            "Id": 42,
            "Player_Name": "RITESH JAGDISH NAGDA",
            "Mobile_Number": 9222133618,
            "Location": "BHANDUP",
            "Village": "MITI UNDOTH",
            "NPL1_NPL2": "NPL-2",
            "Cricket_Type": "Allrounder",
            "TShirt_Size": "XL",
            "Age": 34,
            "Gender": "Male",
            "Payment_SS": "https://drive.google.com/open?id=1qML0LSElUtysP_WtNqcvuIveFaKiKGBS",
            "Photo": "https://drive.google.com/open?id=189UYFDVwkcqnFwLr--nZYQOoL2HHfw7u"
          },
          {
            "Id": 43,
            "Player_Name": "SACHIN JAGDISH NAGDA",
            "Mobile_Number": 9224696075,
            "Location": "BHANDUP",
            "Village": "MOTI UNDOTH",
            "NPL1_NPL2": "Both",
            "Cricket_Type": "Allrounder",
            "TShirt_Size": "XL",
            "Age": 34,
            "Gender": "Male",
            "Payment_SS": "https://drive.google.com/open?id=1iCQBkVxu6_BD45iJ2uhtqkrsJrRXudTd",
            "Photo": "https://drive.google.com/open?id=1hjyydpCScGb7ndupIQ17stAONPxJhf3F"
          },
          {
            "Id": 44,
            "Player_Name": "Chaitanya Vikram Nagda",
            "Mobile_Number": 9326035659,
            "Location": "Chembur",
            "Village": "Naredi",
            "NPL1_NPL2": "None",
            "Cricket_Type": "Bowling",
            "TShirt_Size": "L",
            "Age": 18,
            "Gender": "Male",
            "Payment_SS": "https://drive.google.com/open?id=17wOUC3xKPOYNBsM5xTIMARlkoLrlAL-S",
            "Photo": "https://drive.google.com/open?id=1st5uYMi2L8qKQZ2JUXaHh7uyw9sp5BVu"
          },
          {
            "Id": 45,
            "Player_Name": "Varun Jitendra Shah/Nagda",
            "Mobile_Number": 9819749009,
            "Location": "Santacruz",
            "Village": "Layja",
            "NPL1_NPL2": "Both",
            "Cricket_Type": "Allrounder",
            "TShirt_Size": "L",
            "Age": 34,
            "Gender": "Male",
            "Payment_SS": "https://drive.google.com/open?id=1-Kbmyo0WpT2gidJ8y6G4bClexQIhO9EG",
            "Photo": "https://drive.google.com/open?id=1EB2DVXP6CpsoZBGmXIlUN3ZXcFRzV0t_"
          },
          {
            "Id": 46,
            "Player_Name": "Biren Pravin Nagda",
            "Mobile_Number": 9004071455,
            "Location": "Bhandup",
            "Village": "Sanosara",
            "NPL1_NPL2": "Both",
            "Cricket_Type": "Batting",
            "TShirt_Size": "L",
            "Age": 39,
            "Gender": "Male",
            "Payment_SS": "https://drive.google.com/open?id=1PgwKz0Vc-n9z2AwtjgwJtj3NA8PhlL7w",
            "Photo": "https://drive.google.com/open?id=1ao3HL7iApu4E3oqoTdsq1HgNcjdieqke"
          },
          {
            "Id": 47,
            "Player_Name": "Mehul Vishanji Nagda",
            "Mobile_Number": 9820489899,
            "Location": "Bhandup",
            "Village": "Lathedi",
            "NPL1_NPL2": "Both",
            "Cricket_Type": "Bowling",
            "TShirt_Size": "Xl",
            "Age": 47,
            "Gender": "Male",
            "Payment_SS": "https://drive.google.com/open?id=1YPePqWttSEe_WUelLS4s9i9fo92c82Me",
            "Photo": "https://drive.google.com/open?id=1IL-mmnHUcLZ7P3-ysIOsCn98cdVfAsbH"
          },
          {
            "Id": 48,
            "Player_Name": "DIPESH HIRJI NAGDA",
            "Mobile_Number": 8411042068,
            "Location": "Ambernath",
            "Village": "NAREDI",
            "NPL1_NPL2": "Both",
            "Cricket_Type": "Bowling",
            "TShirt_Size": "M",
            "Age": 38,
            "Gender": "Male",
            "Payment_SS": "https://drive.google.com/open?id=1sARbBAkjJcP2eiTiQjQKL72Y9ipnrRWX",
            "Photo": "https://drive.google.com/open?id=14nJM1VsIMrPHk_M71u4MDH1MqCEm6iTK"
          },
          {
            "Id": 49,
            "Player_Name": "Nilesh hirji nagda",
            "Mobile_Number": 9673040061,
            "Location": "Ambarnath",
            "Village": "Naredi",
            "NPL1_NPL2": "Both",
            "Cricket_Type": "Allrounder",
            "TShirt_Size": "Xl",
            "Age": 35,
            "Gender": "Male",
            "Payment_SS": "https://drive.google.com/open?id=14XHV6WHJ3b03AAjcJVhXy3WASL_k3F_o",
            "Photo": "https://drive.google.com/open?id=1z6hJjftdjm7gMkeGCdIE2eyCCVDWH8IH"
          },
          {
            "Id": 50,
            "Player_Name": "Rohan Vijay Nagda",
            "Mobile_Number": 8652672112,
            "Location": "Dombivli",
            "Village": "Kotdi",
            "NPL1_NPL2": "Both",
            "Cricket_Type": "Allrounder",
            "TShirt_Size": "L-40",
            "Age": 19,
            "Gender": "Male",
            "Payment_SS": "https://drive.google.com/open?id=16lpVXwMHk40OORT7TvCeYzL-ZAU70f1Z",
            "Photo": "https://drive.google.com/open?id=1fEiFw4w4ctAKv8PiUsaldb7-a1OZZDQ_"
          },
          {
            "Id": 51,
            "Player_Name": "Mitesh prabodh nagda",
            "Mobile_Number": 9224130992,
            "Location": "Bhandup",
            "Village": "Moti Undoth",
            "NPL1_NPL2": "NPL-2",
            "Cricket_Type": "Allrounder",
            "TShirt_Size": "M",
            "Age": 35,
            "Gender": "Male",
            "Payment_SS": "https://drive.google.com/open?id=1PknWuqs-_H0lA7x3ebVUvo6Peapw23Zt",
            "Photo": "https://drive.google.com/open?id=1QHniTzIg59HJwueyxqbU7rUseaMZuy3x"
          },
          {
            "Id": 52,
            "Player_Name": "Bhavin Hemendra Nagda",
            "Mobile_Number": 9930098912,
            "Location": "Mulund",
            "Village": "Lathedi",
            "NPL1_NPL2": "Both",
            "Cricket_Type": "Allrounder",
            "TShirt_Size": "XXL (42)",
            "Age": 43,
            "Gender": "Male",
            "Payment_SS": "https://drive.google.com/open?id=1zjYcziKDdE05zmtmu6s9lUFm4xKY6Mau",
            "Photo": "https://drive.google.com/open?id=1smTv2iwsIIZmKwTV27ch7hI4sihKCoQj"
          },
          {
            "Id": 53,
            "Player_Name": "Chintan Jitendra Shah/Nagda",
            "Mobile_Number": 9820361233,
            "Location": "Santacruz",
            "Village": "Mota Layja",
            "NPL1_NPL2": "Both",
            "Cricket_Type": "Bowling",
            "TShirt_Size": "L",
            "Age": 31,
            "Gender": "Male",
            "Payment_SS": "https://drive.google.com/open?id=1CXp6pivzXHxdnB4qg3xqyWhqlgVMLosY",
            "Photo": "https://drive.google.com/open?id=1uDfhGEQVOIqe25-mBm8jEvZ6rVLy2Eha"
          },
          {
            "Id": 54,
            "Player_Name": "Dheer Rajesh Nagda",
            "Mobile_Number": 8655703843,
            "Location": "Mulund",
            "Village": "Makda",
            "NPL1_NPL2": "None",
            "Cricket_Type": "Allrounder",
            "TShirt_Size": "XXL",
            "Age": 22,
            "Gender": "Male",
            "Payment_SS": "https://drive.google.com/open?id=1y8VBcNe9E3fRsIkbnq3NM97y4z5WXPhL",
            "Photo": "https://drive.google.com/open?id=1VW_bGe_zaEyGuiO-pqOlnh83o4_4h_EC"
          },
          {
            "Id": 55,
            "Player_Name": "Rajesh devchand Nagda",
            "Mobile_Number": 8291980836,
            "Location": "Mulund",
            "Village": "Naradi",
            "NPL1_NPL2": "Both",
            "Cricket_Type": "Batting",
            "TShirt_Size": "Xxl",
            "Age": 41,
            "Gender": "Male",
            "Payment_SS": "https://drive.google.com/open?id=1Ugeg-NtzHnB02AVQBTomrvhPivYUPwJB",
            "Photo": "https://drive.google.com/open?id=1bsEVn935P6J-cI4idfDV4A5wgqp6gMUi"
          },
          {
            "Id": 56,
            "Player_Name": "Jasveen Nagda",
            "Mobile_Number": 9004688116,
            "Location": "Dombivli",
            "Village": "Bhojay",
            "NPL1_NPL2": "Both",
            "Cricket_Type": "Allrounder",
            "TShirt_Size": "",
            "Age": 42,
            "Gender": "Male",
            "Payment_SS": "Committee",
            "Photo": "https://drive.google.com/open?id=1Zj2Ww2sXJndVxTIXDY5khWVCkBPdLfH4"
          },
          {
            "Id": 57,
            "Player_Name": "Chintan Rajesh Nagda",
            "Mobile_Number": 9773014397,
            "Location": "",
            "Village": "Makda",
            "NPL1_NPL2": "None",
            "Cricket_Type": "Allrounder",
            "TShirt_Size": "XXL",
            "Age": "",
            "Gender": "Male",
            "Payment_SS": "Paid",
            "Photo": "https://drive.google.com/file/d/1uesY_9_AU0pcx4PSl8HUGQxJPCQ-tDZx/view?usp=sharing"
          },
          {
            "Id": 58,
            "Player_Name": "Vrutik Pravin Nagda",
            "Mobile_Number": 9699521325,
            "Location": "kalyan",
            "Village": "Naredi",
            "NPL1_NPL2": "NPL-2",
            "Cricket_Type": "Allrounder",
            "TShirt_Size": "Xxl",
            "Age": 22,
            "Gender": "Male",
            "Payment_SS": "https://drive.google.com/open?id=1nIV5S-h1Ch9GOVguaavEAf1-bu2-B82h",
            "Photo": "https://drive.google.com/open?id=1pvE3va8ZhzOqv_wQG_o0C3wpN7mwN_-_"
          },
          {
            "Id": 59,
            "Player_Name": "Darshan Ketan Nagda",
            "Mobile_Number": 9930973666,
            "Location": "Vasai",
            "Village": "Dumra",
            "NPL1_NPL2": "None",
            "Cricket_Type": "Allrounder",
            "TShirt_Size": "M",
            "Age": 31,
            "Gender": "Male",
            "Payment_SS": "https://drive.google.com/open?id=1HU-FQySkEpOKU7ebxAhXYZf7rI1nVRrs",
            "Photo": "https://drive.google.com/open?id=1lQHIFWBpVlV7o8gBoAP_kx2Nnq05AXww"
          },
          {
            "Id": 60,
            "Player_Name": "Yash Jayesh Nagda",
            "Mobile_Number": 7738535508,
            "Location": "Mulund",
            "Village": "Naredi",
            "NPL1_NPL2": "None",
            "Cricket_Type": "Bowling",
            "TShirt_Size": "XL",
            "Age": 26,
            "Gender": "Male",
            "Payment_SS": "https://drive.google.com/open?id=1rp2rGwHN3Tvw2zWUM_v1B09c8DCFeMV2",
            "Photo": "https://drive.google.com/open?id=1O_NKM1gXu8JaP3YZruk755DWRZzMNK_6"
          },
          {
            "Id": 61,
            "Player_Name": "Pankhil Deepesh Nagda",
            "Mobile_Number": 8591440332,
            "Location": "Ghatkopar",
            "Village": "Sanosara",
            "NPL1_NPL2": "None",
            "Cricket_Type": "Allrounder",
            "TShirt_Size": "L",
            "Age": 17,
            "Gender": "Male",
            "Payment_SS": "https://drive.google.com/open?id=1criyVK5CIYAOXSj8ujyU4ooIvg_6rmij",
            "Photo": "https://drive.google.com/open?id=1QzPswFN7YDSuo9ohUBe-EUGPGBqbesOu"
          },
          {
            "Id": 62,
            "Player_Name": "Kunjesh Raju Shah/ Nagda",
            "Mobile_Number": 9773550490,
            "Location": "Mulund",
            "Village": "Sanosara",
            "NPL1_NPL2": "None",
            "Cricket_Type": "Allrounder",
            "TShirt_Size": "M",
            "Age": 33,
            "Gender": "Male",
            "Payment_SS": "https://drive.google.com/open?id=1a3RRT3r3a2IW5fpl2BN5dSobqXO4ORyp",
            "Photo": "https://drive.google.com/open?id=1vCQFscwfpoNt77bbaA6d9PUSPLNtXhT0"
          },
          {
            "Id": 63,
            "Player_Name": "Tirth Dewang Nagda",
            "Mobile_Number": 7715055918,
            "Location": "Ghatkopar",
            "Village": "Sanosara/bhuj",
            "NPL1_NPL2": "None",
            "Cricket_Type": "Bowling",
            "TShirt_Size": "M",
            "Age": 15,
            "Gender": "Male",
            "Payment_SS": "https://drive.google.com/open?id=19vx7VMsll-csUcybiDt2-MHnMBPN_Ecu",
            "Photo": "https://drive.google.com/open?id=1ss0BMyXGY8-AnHFMJ_Rs98iqomaDJBdb"
          },
          {
            "Id": 64,
            "Player_Name": "Bhavya Mahendra Nagda",
            "Mobile_Number": 9987526605,
            "Location": "Mulund",
            "Village": "Sanosara",
            "NPL1_NPL2": "NPL-1",
            "Cricket_Type": "Batting",
            "TShirt_Size": "LARGE (L)",
            "Age": 18,
            "Gender": "Male",
            "Payment_SS": "https://drive.google.com/open?id=1zYKCdz68dNkpeOWqnOB3A0anJ4jNQpxu",
            "Photo": "https://drive.google.com/open?id=1EBqMtUo8w1a67M9HiXyDakbFopD8EwT4"
          },
          {
            "Id": 65,
            "Player_Name": "Bhagya Ramesh Nagda",
            "Mobile_Number": 9969591122,
            "Location": "Mulund",
            "Village": "Naredi",
            "NPL1_NPL2": "None",
            "Cricket_Type": "Bowling",
            "TShirt_Size": "M",
            "Age": 19,
            "Gender": "Male",
            "Payment_SS": "https://drive.google.com/open?id=1vKZmHmeJj0146ZHCiTq62LeYxCnjHVNr",
            "Photo": "https://drive.google.com/open?id=1G_dB79uHfHGJH4saj0k3FKQcm4YzYuFS"
          },
          {
            "Id": 66,
            "Player_Name": "Hiren Nanji Nagda",
            "Mobile_Number": 9869319350,
            "Location": "Wadala",
            "Village": "Sanosara",
            "NPL1_NPL2": "None",
            "Cricket_Type": "Allrounder",
            "TShirt_Size": "Xxl",
            "Age": 43,
            "Gender": "Male",
            "Payment_SS": "https://drive.google.com/open?id=1Z4nUoqDuSG3uiS0mDn7ZSMi4h74bQk-x",
            "Photo": "https://drive.google.com/open?id=17gz-UF8k-8NufK-JGkM55OcwQjS-o6bp"
          },
          {
            "Id": 67,
            "Player_Name": "Kunaal dilip nagda",
            "Mobile_Number": 7972554561,
            "Location": "Vasai",
            "Village": "Naredi",
            "NPL1_NPL2": "None",
            "Cricket_Type": "Allrounder",
            "TShirt_Size": "XL",
            "Age": 38,
            "Gender": "Male",
            "Payment_SS": "https://drive.google.com/open?id=1psQDsA39qcuRirNjea1YwmWuf6pdtcig",
            "Photo": "https://drive.google.com/open?id=1cwwszAzop1OqGZHC2zb_koHYy8hYQLsX"
          },
          {
            "Id": 68,
            "Player_Name": "Jay sudhir nagda",
            "Mobile_Number": 8898880881,
            "Location": "Kandivali",
            "Village": "Bhinsara",
            "NPL1_NPL2": "NPL-2",
            "Cricket_Type": "Allrounder",
            "TShirt_Size": "Xxl",
            "Age": 30,
            "Gender": "Male",
            "Payment_SS": "https://drive.google.com/open?id=1rhC3BDhsN63N-9eEJzkww8q1CRYvdXC9",
            "Photo": "https://drive.google.com/open?id=18WsKhsH7Gfj9H6fd_3K0aE6_S_C1H0qd"
          },
          {
            "Id": 69,
            "Player_Name": "Saumya Hemant Nagda",
            "Mobile_Number": 8169433849,
            "Location": "Dombivali",
            "Village": "Bhojay",
            "NPL1_NPL2": "NPL-2",
            "Cricket_Type": "Batting",
            "TShirt_Size": "M",
            "Age": 17,
            "Gender": "Male",
            "Payment_SS": "https://drive.google.com/open?id=1UR7IZg3mo89IBJTXOo4wVOs1b3PgB_lE",
            "Photo": "https://drive.google.com/open?id=1bXU3kK4H-VxG9nQpRszPrA6MWWdCtGJl"
          },
          {
            "Id": 70,
            "Player_Name": "Krish jasveen nagda",
            "Mobile_Number": 9867158589,
            "Location": "Dombivli",
            "Village": "Bhojay",
            "NPL1_NPL2": "Both",
            "Cricket_Type": "Allrounder",
            "TShirt_Size": "L",
            "Age": 15,
            "Gender": "Male",
            "Payment_SS": "https://drive.google.com/open?id=1v784ygYgTcfchJWD4pdTaYgbOdUAAkTF",
            "Photo": "https://drive.google.com/open?id=18IiwGkmzW1B7gzbj6gnEmt3xVKbSbXEA"
          },
          {
            "Id": 71,
            "Player_Name": "Hiren Vasant Shah /Nagda",
            "Mobile_Number": 9321020846,
            "Location": "Sion",
            "Village": "Koday",
            "NPL1_NPL2": "NPL-2",
            "Cricket_Type": "Allrounder",
            "TShirt_Size": "XL",
            "Age": 46,
            "Gender": "Male",
            "Payment_SS": "https://drive.google.com/open?id=16T0-Nh3qzHRJb6ESqkUImtvE2J3Tj2xH",
            "Photo": "https://drive.google.com/open?id=1sASPbCOIxnXwYzhpMBE6B8L9wuykUPj0"
          },
          {
            "Id": 72,
            "Player_Name": "Aayush Akshay Nagda",
            "Mobile_Number": 9821039990,
            "Location": "BORIVALI",
            "Village": "NAREDI",
            "NPL1_NPL2": "None",
            "Cricket_Type": "Batting",
            "TShirt_Size": "L",
            "Age": 25,
            "Gender": "Male",
            "Payment_SS": "https://drive.google.com/open?id=1ctC5hHgzdCU-2mMvBU-fUX_OwBzNciQY",
            "Photo": "https://drive.google.com/open?id=1GTl1LZXiyR8yCeDOFwNKGpp__yPa6uYm"
          },
          {
            "Id": 73,
            "Player_Name": "JAYESH VALLABHJI NAGDA",
            "Mobile_Number": 9967090995,
            "Location": "Mulund checknaka",
            "Village": "Sabharai",
            "NPL1_NPL2": "Both",
            "Cricket_Type": "Allrounder",
            "TShirt_Size": "XXL",
            "Age": 47,
            "Gender": "Male",
            "Payment_SS": "https://drive.google.com/open?id=1VfWMQ14mkP3F5WCMWPNmmOLi9QX63Y_0",
            "Photo": "https://drive.google.com/open?id=1cGmt7oKHYiQSVYt-KF_yiu_tlXeUgslT"
          },
          {
            "Id": 74,
            "Player_Name": "KAVAN JAYESH NAGDA",
            "Mobile_Number": 8928114461,
            "Location": "MULUND CHECKNAKA THANE",
            "Village": "SABHARAI",
            "NPL1_NPL2": "NPL-1",
            "Cricket_Type": "Allrounder",
            "TShirt_Size": "XL",
            "Age": 15.5,
            "Gender": "Male",
            "Payment_SS": "https://drive.google.com/open?id=14CGSPzaJoA_vp7pHj6eEmDpq1EB4cpWp",
            "Photo": "https://drive.google.com/open?id=18usB9co5kRI9vphF4Fmgz81TS78T8wD5"
          },
          {
            "Id": 75,
            "Player_Name": "Jiten Gangji Nagda",
            "Mobile_Number": 9867868060,
            "Location": "Thane",
            "Village": "Moti Undoth",
            "NPL1_NPL2": "None",
            "Cricket_Type": "Allrounder",
            "TShirt_Size": "XL",
            "Age": 40,
            "Gender": "Male",
            "Payment_SS": "https://drive.google.com/open?id=188rDYLs8_KEuVr6CWNe4xQFdkeni16gB",
            "Photo": "https://drive.google.com/open?id=1CM9ucNbafqDsbN6kFzOjevtpSCPhgk_4"
          },
          {
            "Id": 76,
            "Player_Name": "Deep sudhir nagda",
            "Mobile_Number": 9821313321,
            "Location": "Kandivali",
            "Village": "Bhinsara",
            "NPL1_NPL2": "None",
            "Cricket_Type": "Allrounder",
            "TShirt_Size": "Xl",
            "Age": 28,
            "Gender": "Male",
            "Payment_SS": "https://drive.google.com/open?id=1aRchBKSqvGngMDNZAn2rc7FDL9Bq4z0B",
            "Photo": "https://drive.google.com/open?id=142v8YGuhseWrHB_FOyW-RlKa6wrsyJQ-"
          },
          {
            "Id": 77,
            "Player_Name": "Chintan Haresh Nagda",
            "Mobile_Number": 9619715444,
            "Location": "Dombivli",
            "Village": "Naredi",
            "NPL1_NPL2": "None",
            "Cricket_Type": "Batting",
            "TShirt_Size": "S",
            "Age": 23,
            "Gender": "Male",
            "Payment_SS": "https://drive.google.com/open?id=1imH45PuygT8_iNkh-5vUEhH8c3pNy8lg",
            "Photo": "https://drive.google.com/open?id=1sDKjS-shRdxo7dvC9za9-ff4mkgIrX85"
          },
          {
            "Id": 78,
            "Player_Name": "Mitesh Dhanji Nagda",
            "Mobile_Number": 9702730797,
            "Location": "Mulund",
            "Village": "Changdai",
            "NPL1_NPL2": "Both",
            "Cricket_Type": "Allrounder",
            "TShirt_Size": "",
            "Age": 43,
            "Gender": "Male",
            "Payment_SS": "Remaining",
            "Photo": "https://drive.google.com/open?id=1iYVGZTuJFz0L8rfsz-xCojgKjp4To0ka"
          },
          {
            "Id": 79,
            "Player_Name": "Sangeet Mitesh nagda",
            "Mobile_Number": 9702730797,
            "Location": "Mulund",
            "Village": "Changdai",
            "NPL1_NPL2": "Both",
            "Cricket_Type": "Bowler",
            "TShirt_Size": "",
            "Age": 17,
            "Gender": "Male",
            "Payment_SS": "Remaining",
            "Photo": "https://drive.google.com/open?id=1_GAb4oiwRbJbDfmxiqGfaG7o5yGdicSC"
          },
          {
            "Id": 80,
            "Player_Name": "Sahil Mitesh Nagda",
            "Mobile_Number": 9702730797,
            "Location": "Mulund",
            "Village": "Changdai",
            "NPL1_NPL2": "Both",
            "Cricket_Type": "Allrounder",
            "TShirt_Size": "",
            "Age": 17,
            "Gender": "Male",
            "Payment_SS": "Remaining",
            "Photo": "https://drive.google.com/open?id=148C4p5WK-8ulpAqsbpkglVAIZSBE9v3V"
          },
          {
            "Id": 81,
            "Player_Name": "Alpesh Nagda",
            "Mobile_Number": 9224417423,
            "Location": "Bhandup",
            "Village": "Unodth",
            "NPL1_NPL2": "NPL-1",
            "Cricket_Type": "Allrounder",
            "TShirt_Size": "",
            "Age": 40,
            "Gender": "Male",
            "Payment_SS": "Remaining",
            "Photo": "https://drive.google.com/open?id=15YKtQEZOjWEUegydpMcWsdRYtbbIYYEk"
          },
          {
            "Id": 82,
            "Player_Name": "Veer Alpesh Nagda",
            "Mobile_Number": 7977980700,
            "Location": "Bhandup",
            "Village": "Unodth",
            "NPL1_NPL2": "NPL-1",
            "Cricket_Type": "Allrounder",
            "TShirt_Size": "",
            "Age": 17,
            "Gender": "Male",
            "Payment_SS": "Remaining",
            "Photo": "https://drive.google.com/open?id=10jLKjFpIl5hWb5Y_BCpZ22suQSFo1rjE"
          },
          {
            "Id": 83,
            "Player_Name": "Tarun Morarji nagda",
            "Mobile_Number": 9324767000,
            "Location": "Kalyan",
            "Village": "Naredi",
            "NPL1_NPL2": "NPL-1",
            "Cricket_Type": "Allrounder",
            "TShirt_Size": "L",
            "Age": 42,
            "Gender": "Male",
            "Payment_SS": "Remaining",
            "Photo": "https://drive.google.com/open?id=1ySRJzBFcgKSuzKjsxEwdruq0nRpiMw-j"
          },
          {
            "Id": 84,
            "Player_Name": "Ronak praful nagda",
            "Mobile_Number": "96642 35011",
            "Location": "Dombivli",
            "Village": "Kharua",
            "NPL1_NPL2": "None",
            "Cricket_Type": "Allrounder",
            "TShirt_Size": "",
            "Age": 30,
            "Gender": "Male",
            "Payment_SS": "Remaining",
            "Photo": "https://drive.google.com/open?id=1NHYK8q9bu1OKjeJGaN3w6Kzdwtx6Y9H9"
          }
        ];
   }
}