  export const PlayerData = {
       getData : function () {
        return [
            {
              "Id": 1,
              "Player_Name": "Palak Chetan Nagda",
              "Mobile_Number": 9819121888,
              "Location": "Mulund",
              "Village": "Kotdi Mahadevpuri",
              "NPL1_NPL2": "NPL-2",
              "Cricket_Type": "Bowling",
              "TShirt_Size": "L",
              "Age": 20,
              "Gender": "Female",
              "Payment_SS": "https://drive.google.com/open?id=1yE0N8oJ9pelbliArALdkl1qVPAzykuzv",
              "Photo": "https://drive.google.com/open?id=1W_-qAVxM97mLs4Xn2b8apRsKlPX_Nr42",
              "Email_Id": "nagda.palak@gmail.com",
              "": "",
              "__1": ""
            },
            {
              "Id": 2,
              "Player_Name": "Tina Mahesh Nagda",
              "Mobile_Number": 7738001110,
              "Location": "Mulund",
              "Village": "Kotadi Mahadevpuri",
              "NPL1_NPL2": "NPL-2",
              "Cricket_Type": "Allrounder",
              "TShirt_Size": "M",
              "Age": 43,
              "Gender": "Female",
              "Payment_SS": "https://drive.google.com/open?id=1H7emhHE_DofMh6A3sUYCiYEV8EyVlmzp",
              "Photo": "https://drive.google.com/open?id=1vx8rjDRtg0uHUS9kr_JInXD3jxcTQKDM",
              "Email_Id": "Nagda.tina@gmail.com",
              "": "",
              "__1": ""
            },
            {
              "Id": 3,
              "Player_Name": "Nirali Nirav Rambhia - Nagda",
              "Mobile_Number": 8169796917,
              "Location": "Dombivali",
              "Village": "Nana bhadiya",
              "NPL1_NPL2": "None",
              "Cricket_Type": "Batting",
              "TShirt_Size": "S",
              "Age": 27,
              "Gender": "Niyani",
              "Payment_SS": "https://drive.google.com/open?id=1sOQWCoJxtvl_fAVrnRT8R3_v3T-VDwaX",
              "Photo": "https://drive.google.com/open?id=15fSVBsTdjhzOSTF6i1reXW6CuMRhCuaF",
              "Email_Id": "nirushah96@gmail.com",
              "": "",
              "__1": ""
            },
            {
              "Id": 4,
              "Player_Name": "Nidhi Vaibhav Nagda",
              "Mobile_Number": 9820008246,
              "Location": "Bhandup",
              "Village": "Dumra",
              "NPL1_NPL2": "NPL-2",
              "Cricket_Type": "Allrounder",
              "TShirt_Size": "L",
              "Age": 28,
              "Gender": "Female",
              "Payment_SS": "https://drive.google.com/open?id=1TxnxDAL5-IS49aoyc6R3HH6H4od4nIUz",
              "Photo": "https://drive.google.com/open?id=14F6exa71kotKz40ej1C5o_krdmW2mQpw",
              "Email_Id": "marunidhi25@gmail.com",
              "": "",
              "__1": ""
            },
            {
              "Id": 5,
              "Player_Name": "Priyanka Chirag sangoi",
              "Mobile_Number": 7066845446,
              "Location": "Ambarnath",
              "Village": "Bada",
              "NPL1_NPL2": "None",
              "Cricket_Type": "Allrounder",
              "TShirt_Size": "XL",
              "Age": 35,
              "Gender": "Niyani",
              "Payment_SS": "https://drive.google.com/open?id=1ntWhMahvVzf6cm0Bs9m29Tm_-WHKuI4k",
              "Photo": "https://drive.google.com/open?id=1k6SqD5XYbmMKy96Y2EVm1YvaZce8uiyS",
              "Email_Id": "Priyanka.sangoi@gmail.com",
              "": "",
              "__1": ""
            },
            {
              "Id": 6,
              "Player_Name": "Harsha Mukesh Dedhia",
              "Mobile_Number": 8108391887,
              "Location": "Mulund west",
              "Village": "Nagalpur",
              "NPL1_NPL2": "NPL-2",
              "Cricket_Type": "Allrounder",
              "TShirt_Size": "XL",
              "Age": 54,
              "Gender": "Female",
              "Payment_SS": "https://drive.google.com/open?id=1Gf_8cEUJbv9xXesNGoulxJbS4ELN2nsP",
              "Photo": "https://drive.google.com/open?id=162OBHwIqJ__KTsgZ2OG-24umGqEejOJz",
              "Email_Id": "jaydedhia422@gmail.com",
              "": "",
              "__1": ""
            },
            {
              "Id": 7,
              "Player_Name": "Avani Samir Nagda",
              "Mobile_Number": 7977290668,
              "Location": "Mulund",
              "Village": "Bhojay",
              "NPL1_NPL2": "Both",
              "Cricket_Type": "Bowling",
              "TShirt_Size": "XXL",
              "Age": 35,
              "Gender": "Female",
              "Payment_SS": "https://drive.google.com/open?id=17lgGY_VfJbUD0GKwibU9b0TFXAE3vYpb",
              "Photo": "https://drive.google.com/open?id=1g3v6OVYQUmNElEU3AuNgbcDA5Tbeg9Uq",
              "Email_Id": "avaninagda365@gmail.com",
              "": "",
              "__1": ""
            },
            {
              "Id": 8,
              "Player_Name": "Tina Kamlesh Rambhia",
              "Mobile_Number": 9769454691,
              "Location": "Mulund",
              "Village": "Vinjan",
              "NPL1_NPL2": "NPL-2",
              "Cricket_Type": "Bowling",
              "TShirt_Size": "XL",
              "Age": 57,
              "Gender": "Niyani",
              "Payment_SS": "https://drive.google.com/open?id=1xctNiQMztqGFqx3JyhTXFmD4Giexipw4",
              "Photo": "https://drive.google.com/open?id=1vxgxPT0MOl9F-bbrSGVMH-AwY0_KaZ-b",
              "Email_Id": "tinarambhia28@gmail.com",
              "": "",
              "__1": ""
            },
            {
              "Id": 9,
              "Player_Name": "Jinal Bhavesh Nagda",
              "Mobile_Number": 9987407527,
              "Location": "Vashi (Navi Mumbai)",
              "Village": "Changdai",
              "NPL1_NPL2": "Both",
              "Cricket_Type": "Bowling",
              "TShirt_Size": "M",
              "Age": 35,
              "Gender": "Female",
              "Payment_SS": "https://drive.google.com/open?id=1Cq9AQruTNKrs-h__2rID2YszGrnamc3X",
              "Photo": "https://drive.google.com/open?id=1BUBuMRytILr5zqtI2rFYHhze-QFkEx_K",
              "Email_Id": "jinalbnagda@gmail.com",
              "": "",
              "__1": ""
            },
            {
              "Id": 10,
              "Player_Name": "Mayuri Hitendra Nagda",
              "Mobile_Number": 9819455775,
              "Location": "Dombivli",
              "Village": "Sanosara",
              "NPL1_NPL2": "Both",
              "Cricket_Type": "Batting",
              "TShirt_Size": "XL",
              "Age": 35,
              "Gender": "Female",
              "Payment_SS": "https://drive.google.com/open?id=11tJbvCYSgWUaGU6jkHbj0fLyP7O72TFc",
              "Photo": "https://drive.google.com/open?id=1sWVTvtSeAoM40zNBbxUztBrSdJLTUYfx",
              "Email_Id": "mayurinagada11@gmail.com",
              "": "",
              "__1": ""
            },
            {
              "Id": 11,
              "Player_Name": "Pooja Hardik Nagda",
              "Mobile_Number": 8080903513,
              "Location": "Mulund",
              "Village": "Vindh",
              "NPL1_NPL2": "None",
              "Cricket_Type": "Bowling",
              "TShirt_Size": "M",
              "Age": 28,
              "Gender": "Female",
              "Payment_SS": "https://drive.google.com/open?id=13_gklRl9ytrP0YpO9Tl-aGBn0PZtX-Q8",
              "Photo": "https://drive.google.com/open?id=1hmevVbhxIyxTi50dAvwLHASt5bIpWhT6",
              "Email_Id": "pspooja751@gmail.com",
              "": "",
              "__1": ""
            },
            {
              "Id": 12,
              "Player_Name": "Chandrika Harakchand Nagda",
              "Mobile_Number": 9821189801,
              "Location": "Mulund",
              "Village": "Vindh",
              "NPL1_NPL2": "NPL-2",
              "Cricket_Type": "Allrounder",
              "TShirt_Size": "XXL",
              "Age": 52,
              "Gender": "Female",
              "Payment_SS": "https://drive.google.com/open?id=1aFQhoi5frkAlbCCzHXBluZ0Ir3QU3RG1",
              "Photo": "https://drive.google.com/open?id=1JQ0fxXF-WVQXURe9LAaHRjskaQ-_8EFX",
              "Email_Id": "nchand1971@gmail.com",
              "": "",
              "__1": ""
            },
            {
              "Id": 13,
              "Player_Name": "Nandita Mehul Shah/Nagda",
              "Mobile_Number": 9920896533,
              "Location": "Mulund",
              "Village": "Sanosara",
              "NPL1_NPL2": "None",
              "Cricket_Type": "Allrounder",
              "TShirt_Size": "Medium",
              "Age": 42,
              "Gender": "Female",
              "Payment_SS": "https://drive.google.com/open?id=1Y51ebPdaEsisrYoZWphUpXEf5-unyYnN",
              "Photo": "https://drive.google.com/open?id=1uFR5L3AJA6Q1eJk7HoUuoSSt5l_XRFzI",
              "Email_Id": "nanditams@gmail.com",
              "": "",
              "__1": ""
            },
            {
              "Id": 14,
              "Player_Name": "Geeta Bhavesh Nagda",
              "Mobile_Number": 9152585975,
              "Location": "Mulund east",
              "Village": "Sanosara",
              "NPL1_NPL2": "NPL-1",
              "Cricket_Type": "Allrounder",
              "TShirt_Size": "S",
              "Age": 50,
              "Gender": "Female",
              "Payment_SS": "https://drive.google.com/open?id=1yXLfkVZB1GgqCcujBPTkmDs7jfrSfvN6",
              "Photo": "https://drive.google.com/open?id=1tCglrX74KaffxBat_V-qCR_gZqztd7Ib",
              "Email_Id": "geetabnagda43@gmail.com",
              "": "",
              "__1": ""
            },
            {
              "Id": 15,
              "Player_Name": "Ami bhavin nagda",
              "Mobile_Number": 9930411453,
              "Location": "Bhayandar",
              "Village": "Moti undoth",
              "NPL1_NPL2": "NPL-2",
              "Cricket_Type": "Bowling",
              "TShirt_Size": "Xxl",
              "Age": 37,
              "Gender": "Female",
              "Payment_SS": "https://drive.google.com/open?id=1xUUWg7ZjJUbglxMDyFnkBdea97UbUEQf",
              "Photo": "https://drive.google.com/open?id=1CceunkxHJ5KcpQjj_xeZkKtqo3Mtc4iR",
              "Email_Id": "amidedhia99@gmail.com",
              "": "",
              "__1": ""
            },
            {
              "Id": 16,
              "Player_Name": "Bhoomee Chandresh Nagda",
              "Mobile_Number": 8356872378,
              "Location": "Bhandup",
              "Village": "MOTI UNODTH",
              "NPL1_NPL2": "NPL-2",
              "Cricket_Type": "Allrounder",
              "TShirt_Size": "4XL",
              "Age": 16,
              "Gender": "Female",
              "Payment_SS": "https://drive.google.com/open?id=12rdkE2H7UgVSeN272yKJTINWfRUWwu-P",
              "Photo": "https://drive.google.com/open?id=1FzzVbQ7J_IrX3F5u1wUegtqIOR8LM6AW",
              "Email_Id": "phgala02@gmail.com",
              "": "",
              "__1": ""
            },
            {
              "Id": 17,
              "Player_Name": "Kashmira Chandresh Nagda",
              "Mobile_Number": 9167534774,
              "Location": "Bhandup",
              "Village": "Moti Undoth",
              "NPL1_NPL2": "NPL-2",
              "Cricket_Type": "Allrounder",
              "TShirt_Size": "5XL",
              "Age": 40,
              "Gender": "Female",
              "Payment_SS": "https://drive.google.com/open?id=111qsW-2rs-n45go7N7ZV8tLIqvIpl2Qe",
              "Photo": "https://drive.google.com/open?id=18vCc3nRo_5sl1zYCGR6p_CCJDMTuAtKW",
              "Email_Id": "phgala03@gmail.com",
              "": "",
              "__1": ""
            },
            {
              "Id": 18,
              "Player_Name": "Ishita Rupesh Nagda",
              "Mobile_Number": 9892101963,
              "Location": "Goregaon",
              "Village": "Sanosara",
              "NPL1_NPL2": "NPL-2",
              "Cricket_Type": "Allrounder",
              "TShirt_Size": "S",
              "Age": 20,
              "Gender": "Niyani",
              "Payment_SS": "https://drive.google.com/open?id=1JhXZPWdb2Trh0mwOQJ6NrGFhPI5v6dKm",
              "Photo": "https://drive.google.com/open?id=1HIjvMW_semZtx27G8UtWaXfe9dxbGoZr",
              "Email_Id": "ishitanagda25@gmail.com",
              "": "",
              "__1": ""
            },
            {
              "Id": 19,
              "Player_Name": "Daksha Jitendra Shah/Nagda",
              "Mobile_Number": 9820557716,
              "Location": "Santacruz",
              "Village": "Mota Layja",
              "NPL1_NPL2": "NPL-2",
              "Cricket_Type": "Bowling",
              "TShirt_Size": "XL",
              "Age": 58,
              "Gender": "Female",
              "Payment_SS": "https://drive.google.com/open?id=1WIAgl2Ylrd9OHWiT4x5_KeVkk-9dmu-y",
              "Photo": "https://drive.google.com/open?id=1t45PSmlkcONucNxfltNXaUrJYMaa_LSE",
              "Email_Id": "alpsbeautycare@gmail.com",
              "": "",
              "__1": ""
            }
    ];
       }
        
    }

