  
  export const PlayerData = {
       getData : function () {
        return [
          {
            "Id": 1,
            "Player_Name": "Palak Chetan Nagda",
            "Mobile_Number": 9819121888,
            "Location": "Mulund",
            "Village": "Kotdi Mahadevpuri",
            "NPL1_NPL2": "NPL-2",
            "Cricket_Type": "Bowling",
            "TShirt_Size": "L",
            "Age": 20,
            "Gender": "Female",
            "Payment_SS": "https://drive.google.com/open?id=1yE0N8oJ9pelbliArALdkl1qVPAzykuzv",
            "Photo": "https://drive.google.com/open?id=1W_-qAVxM97mLs4Xn2b8apRsKlPX_Nr42",
            "Email_Id": "nagda.palak@gmail.com"
          },
          {
            "Id": 2,
            "Player_Name": "Tina Mahesh Nagda",
            "Mobile_Number": 7738001110,
            "Location": "Mulund",
            "Village": "Kotadi Mahadevpuri",
            "NPL1_NPL2": "NPL-2",
            "Cricket_Type": "Allrounder",
            "TShirt_Size": "M",
            "Age": 43,
            "Gender": "Female",
            "Payment_SS": "https://drive.google.com/open?id=1H7emhHE_DofMh6A3sUYCiYEV8EyVlmzp",
            "Photo": "https://drive.google.com/open?id=1vx8rjDRtg0uHUS9kr_JInXD3jxcTQKDM",
            "Email_Id": "Nagda.tina@gmail.com"
          },
          {
            "Id": 3,
            "Player_Name": "Nirali Nirav Rambhia - Nagda",
            "Mobile_Number": 8169796917,
            "Location": "Dombivali",
            "Village": "Nana bhadiya",
            "NPL1_NPL2": "None",
            "Cricket_Type": "Batting",
            "TShirt_Size": "S",
            "Age": 27,
            "Gender": "Niyani",
            "Payment_SS": "https://drive.google.com/open?id=1sOQWCoJxtvl_fAVrnRT8R3_v3T-VDwaX",
            "Photo": "https://drive.google.com/open?id=15fSVBsTdjhzOSTF6i1reXW6CuMRhCuaF",
            "Email_Id": "nirushah96@gmail.com"
          },
          {
            "Id": 4,
            "Player_Name": "Nidhi Vaibhav Nagda",
            "Mobile_Number": 9820008246,
            "Location": "Bhandup",
            "Village": "Dumra",
            "NPL1_NPL2": "NPL-2",
            "Cricket_Type": "Allrounder",
            "TShirt_Size": "L",
            "Age": 28,
            "Gender": "Female",
            "Payment_SS": "https://drive.google.com/open?id=1TxnxDAL5-IS49aoyc6R3HH6H4od4nIUz",
            "Photo": "https://drive.google.com/open?id=14F6exa71kotKz40ej1C5o_krdmW2mQpw",
            "Email_Id": "marunidhi25@gmail.com"
          },
          {
            "Id": 5,
            "Player_Name": "Priyanka Chirag sangoi",
            "Mobile_Number": 7066845446,
            "Location": "Ambarnath",
            "Village": "Bada",
            "NPL1_NPL2": "None",
            "Cricket_Type": "Allrounder",
            "TShirt_Size": "XL",
            "Age": 35,
            "Gender": "Niyani",
            "Payment_SS": "https://drive.google.com/open?id=1ntWhMahvVzf6cm0Bs9m29Tm_-WHKuI4k",
            "Photo": "https://drive.google.com/open?id=1k6SqD5XYbmMKy96Y2EVm1YvaZce8uiyS",
            "Email_Id": "Priyanka.sangoi@gmail.com"
          },
          {
            "Id": 6,
            "Player_Name": "Harsha Mukesh Dedhia",
            "Mobile_Number": 8108391887,
            "Location": "Mulund west",
            "Village": "Nagalpur",
            "NPL1_NPL2": "NPL-2",
            "Cricket_Type": "Allrounder",
            "TShirt_Size": "XL",
            "Age": 54,
            "Gender": "Female",
            "Payment_SS": "https://drive.google.com/open?id=1Gf_8cEUJbv9xXesNGoulxJbS4ELN2nsP",
            "Photo": "https://drive.google.com/open?id=162OBHwIqJ__KTsgZ2OG-24umGqEejOJz",
            "Email_Id": "jaydedhia422@gmail.com"
          },
          {
            "Id": 7,
            "Player_Name": "Avani Samir Nagda",
            "Mobile_Number": 7977290668,
            "Location": "Mulund",
            "Village": "Bhojay",
            "NPL1_NPL2": "Both",
            "Cricket_Type": "Bowling",
            "TShirt_Size": "XXL",
            "Age": 35,
            "Gender": "Female",
            "Payment_SS": "https://drive.google.com/open?id=17lgGY_VfJbUD0GKwibU9b0TFXAE3vYpb",
            "Photo": "https://drive.google.com/open?id=1g3v6OVYQUmNElEU3AuNgbcDA5Tbeg9Uq",
            "Email_Id": "avaninagda365@gmail.com"
          },
          {
            "Id": 8,
            "Player_Name": "Tina Kamlesh Rambhia",
            "Mobile_Number": 9769454691,
            "Location": "Mulund",
            "Village": "Vinjan",
            "NPL1_NPL2": "NPL-2",
            "Cricket_Type": "Bowling",
            "TShirt_Size": "XL",
            "Age": 57,
            "Gender": "Niyani",
            "Payment_SS": "https://drive.google.com/open?id=1xctNiQMztqGFqx3JyhTXFmD4Giexipw4",
            "Photo": "https://drive.google.com/open?id=1vxgxPT0MOl9F-bbrSGVMH-AwY0_KaZ-b",
            "Email_Id": "tinarambhia28@gmail.com"
          },
          {
            "Id": 9,
            "Player_Name": "Jinal Bhavesh Nagda",
            "Mobile_Number": 9987407527,
            "Location": "Vashi (Navi Mumbai)",
            "Village": "Changdai",
            "NPL1_NPL2": "Both",
            "Cricket_Type": "Bowling",
            "TShirt_Size": "M",
            "Age": 35,
            "Gender": "Female",
            "Payment_SS": "https://drive.google.com/open?id=1Cq9AQruTNKrs-h__2rID2YszGrnamc3X",
            "Photo": "https://drive.google.com/open?id=1BUBuMRytILr5zqtI2rFYHhze-QFkEx_K",
            "Email_Id": "jinalbnagda@gmail.com"
          },
          {
            "Id": 10,
            "Player_Name": "Mayuri Hitendra Nagda",
            "Mobile_Number": 9819455775,
            "Location": "Dombivli",
            "Village": "Sanosara",
            "NPL1_NPL2": "Both",
            "Cricket_Type": "Batting",
            "TShirt_Size": "XL",
            "Age": 35,
            "Gender": "Female",
            "Payment_SS": "https://drive.google.com/open?id=11tJbvCYSgWUaGU6jkHbj0fLyP7O72TFc",
            "Photo": "https://drive.google.com/open?id=1sWVTvtSeAoM40zNBbxUztBrSdJLTUYfx",
            "Email_Id": "mayurinagada11@gmail.com"
          },
          {
            "Id": 11,
            "Player_Name": "Pooja Hardik Nagda",
            "Mobile_Number": 8080903513,
            "Location": "Mulund",
            "Village": "Vindh",
            "NPL1_NPL2": "None",
            "Cricket_Type": "Bowling",
            "TShirt_Size": "M",
            "Age": 28,
            "Gender": "Female",
            "Payment_SS": "https://drive.google.com/open?id=13_gklRl9ytrP0YpO9Tl-aGBn0PZtX-Q8",
            "Photo": "https://drive.google.com/open?id=1hmevVbhxIyxTi50dAvwLHASt5bIpWhT6",
            "Email_Id": "pspooja751@gmail.com"
          },
          {
            "Id": 12,
            "Player_Name": "Chandrika Harakchand Nagda",
            "Mobile_Number": 9821189801,
            "Location": "Mulund",
            "Village": "Vindh",
            "NPL1_NPL2": "NPL-2",
            "Cricket_Type": "Allrounder",
            "TShirt_Size": "XXL",
            "Age": 52,
            "Gender": "Female",
            "Payment_SS": "https://drive.google.com/open?id=1aFQhoi5frkAlbCCzHXBluZ0Ir3QU3RG1",
            "Photo": "https://drive.google.com/open?id=1JQ0fxXF-WVQXURe9LAaHRjskaQ-_8EFX",
            "Email_Id": "nchand1971@gmail.com"
          },
          {
            "Id": 13,
            "Player_Name": "Nandita Mehul Shah/Nagda",
            "Mobile_Number": 9920896533,
            "Location": "Mulund",
            "Village": "Sanosara",
            "NPL1_NPL2": "None",
            "Cricket_Type": "Allrounder",
            "TShirt_Size": "Medium",
            "Age": 42,
            "Gender": "Female",
            "Payment_SS": "https://drive.google.com/open?id=1Y51ebPdaEsisrYoZWphUpXEf5-unyYnN",
            "Photo": "https://drive.google.com/open?id=1uFR5L3AJA6Q1eJk7HoUuoSSt5l_XRFzI",
            "Email_Id": "nanditams@gmail.com"
          },
          {
            "Id": 14,
            "Player_Name": "Geeta Bhavesh Nagda",
            "Mobile_Number": 9152585975,
            "Location": "Mulund east",
            "Village": "Sanosara",
            "NPL1_NPL2": "NPL-1",
            "Cricket_Type": "Allrounder",
            "TShirt_Size": "S",
            "Age": 50,
            "Gender": "Female",
            "Payment_SS": "https://drive.google.com/open?id=1yXLfkVZB1GgqCcujBPTkmDs7jfrSfvN6",
            "Photo": "https://drive.google.com/open?id=1tCglrX74KaffxBat_V-qCR_gZqztd7Ib",
            "Email_Id": "geetabnagda43@gmail.com"
          },
          {
            "Id": 15,
            "Player_Name": "Ami bhavin nagda",
            "Mobile_Number": 9930411453,
            "Location": "Bhayandar",
            "Village": "Moti undoth",
            "NPL1_NPL2": "NPL-2",
            "Cricket_Type": "Bowling",
            "TShirt_Size": "Xxl",
            "Age": 37,
            "Gender": "Female",
            "Payment_SS": "https://drive.google.com/open?id=1xUUWg7ZjJUbglxMDyFnkBdea97UbUEQf",
            "Photo": "https://drive.google.com/open?id=1CceunkxHJ5KcpQjj_xeZkKtqo3Mtc4iR",
            "Email_Id": "amidedhia99@gmail.com"
          },
          {
            "Id": 16,
            "Player_Name": "Bhoomee Chandresh Nagda",
            "Mobile_Number": 8356872378,
            "Location": "Bhandup",
            "Village": "MOTI UNODTH",
            "NPL1_NPL2": "NPL-2",
            "Cricket_Type": "Allrounder",
            "TShirt_Size": "4XL",
            "Age": 16,
            "Gender": "Female",
            "Payment_SS": "https://drive.google.com/open?id=12rdkE2H7UgVSeN272yKJTINWfRUWwu-P",
            "Photo": "https://drive.google.com/open?id=1FzzVbQ7J_IrX3F5u1wUegtqIOR8LM6AW",
            "Email_Id": "phgala02@gmail.com"
          },
          {
            "Id": 17,
            "Player_Name": "Kashmira Chandresh Nagda",
            "Mobile_Number": 9167534774,
            "Location": "Bhandup",
            "Village": "Moti Undoth",
            "NPL1_NPL2": "NPL-2",
            "Cricket_Type": "Allrounder",
            "TShirt_Size": "5XL",
            "Age": 40,
            "Gender": "Female",
            "Payment_SS": "https://drive.google.com/open?id=111qsW-2rs-n45go7N7ZV8tLIqvIpl2Qe",
            "Photo": "https://drive.google.com/open?id=18vCc3nRo_5sl1zYCGR6p_CCJDMTuAtKW",
            "Email_Id": "phgala03@gmail.com"
          },
          {
            "Id": 18,
            "Player_Name": "Ishita Rupesh Nagda",
            "Mobile_Number": 9892101963,
            "Location": "Goregaon",
            "Village": "Sanosara",
            "NPL1_NPL2": "NPL-2",
            "Cricket_Type": "Allrounder",
            "TShirt_Size": "S",
            "Age": 20,
            "Gender": "Niyani",
            "Payment_SS": "https://drive.google.com/open?id=1JhXZPWdb2Trh0mwOQJ6NrGFhPI5v6dKm",
            "Photo": "https://drive.google.com/open?id=1HIjvMW_semZtx27G8UtWaXfe9dxbGoZr",
            "Email_Id": "ishitanagda25@gmail.com"
          },
          {
            "Id": 19,
            "Player_Name": "Daksha Jitendra Shah/Nagda",
            "Mobile_Number": 9820557716,
            "Location": "Santacruz",
            "Village": "Mota Layja",
            "NPL1_NPL2": "NPL-2",
            "Cricket_Type": "Bowling",
            "TShirt_Size": "XL",
            "Age": 58,
            "Gender": "Female",
            "Payment_SS": "https://drive.google.com/open?id=1WIAgl2Ylrd9OHWiT4x5_KeVkk-9dmu-y",
            "Photo": "https://drive.google.com/open?id=1t45PSmlkcONucNxfltNXaUrJYMaa_LSE",
            "Email_Id": "alpsbeautycare@gmail.com"
          },
          {
            "Id": 20,
            "Player_Name": "Jayshree kalpesh Nagda",
            "Mobile_Number": 9619016426,
            "Location": "Thane",
            "Village": "Sanosara",
            "NPL1_NPL2": "NPL-2",
            "Cricket_Type": "Bowling",
            "TShirt_Size": "Xl",
            "Age": 43,
            "Gender": "Female",
            "Payment_SS": "https://drive.google.com/open?id=1dvfWY8oGZqPVzQSn2PA5b2kUMykQ6KzG",
            "Photo": "https://drive.google.com/open?id=1cxUtFjudjPUBFKKVkeV50F0ZkDuo1I86",
            "Email_Id": "jevdshah@gmail.com"
          },
          {
            "Id": 21,
            "Player_Name": "Shraddha Rupesh Nagda",
            "Mobile_Number": 7208071172,
            "Location": "Bhayandar",
            "Village": "Naredi",
            "NPL1_NPL2": "Both",
            "Cricket_Type": "Allrounder",
            "TShirt_Size": "Xl",
            "Age": 40,
            "Gender": "Female",
            "Payment_SS": "https://drive.google.com/open?id=1UZUujxKXwO5WWPkq0_bKxBRmrnw0I9iF",
            "Photo": "https://drive.google.com/open?id=1JilSixUeSGJhS2Y3NStgSN_q-xHDBFFs",
            "Email_Id": "shraddha.nagda@gmail.com"
          },
          {
            "Id": 22,
            "Player_Name": "Akshata sagar gala",
            "Mobile_Number": 9820836260,
            "Location": "Mulund",
            "Village": "Bhojay",
            "NPL1_NPL2": "NPL-2",
            "Cricket_Type": "Allrounder",
            "TShirt_Size": "3xl",
            "Age": 31,
            "Gender": "Female",
            "Payment_SS": "https://drive.google.com/open?id=1n_2uDyyIsBB1W9zz3RvMvQ1Rg6V-EpTl",
            "Photo": "https://drive.google.com/open?id=1EBH6KyOkKRM9tHQl83CS5NRXB0XQfqFG",
            "Email_Id": "Nagdaakshata@gmail.com"
          },
          {
            "Id": 23,
            "Player_Name": "Vaishali Deepak Pasad",
            "Mobile_Number": 9619703328,
            "Location": "Mulund Checknaka west",
            "Village": "Bhojay",
            "NPL1_NPL2": "NPL-2",
            "Cricket_Type": "Bowling",
            "TShirt_Size": "M",
            "Age": 47,
            "Gender": "Niyani",
            "Payment_SS": "https://drive.google.com/open?id=1HjKoXR_r9MsNjRZbfcfvJ8Wrx0f7-ggz",
            "Photo": "https://drive.google.com/open?id=1NXKbAiw0UlqGYPyO6P0eVesWUfX2uX0-",
            "Email_Id": "Vaishalipasad2310@gmail.co"
          },
          {
            "Id": 24,
            "Player_Name": "Jiya rupesh nagda",
            "Mobile_Number": 9821483687,
            "Location": "Bhayandar",
            "Village": "Naredi",
            "NPL1_NPL2": "Both",
            "Cricket_Type": "Allrounder",
            "TShirt_Size": "M",
            "Age": 16,
            "Gender": "Female",
            "Payment_SS": "https://drive.google.com/open?id=18ZrgMG6X6qmuMumyJh4VQJeU1THqLZMQ",
            "Photo": "https://drive.google.com/open?id=1Na8MUy0AEvAg6DjL89pso1lM6vYkbflh",
            "Email_Id": "Vdedhia38@gmail.com"
          },
          {
            "Id": 25,
            "Player_Name": "Bhumi Paresh Nagda",
            "Mobile_Number": 7385520946,
            "Location": "Dombivali East",
            "Village": "Vidh",
            "NPL1_NPL2": "Both",
            "Cricket_Type": "Allrounder",
            "TShirt_Size": "S",
            "Age": 23,
            "Gender": "Female",
            "Payment_SS": "https://drive.google.com/open?id=1k99mcRyPkhRNjR8-sqdJmeFvlPvf2T0g",
            "Photo": "https://drive.google.com/open?id=1VRiu8ILcjxF0CHXlK1lpgKtLdzJen0MK",
            "Email_Id": "bhuminagda2000@gmail.com"
          },
          {
            "Id": 26,
            "Player_Name": "Chaitri Dhiraj Nagda",
            "Mobile_Number": 9324070874,
            "Location": "Malad",
            "Village": "Dumra",
            "NPL1_NPL2": "None",
            "Cricket_Type": "Allrounder",
            "TShirt_Size": "L",
            "Age": 19,
            "Gender": "Niyani",
            "Payment_SS": "https://drive.google.com/open?id=1kwE4Xv_2I9uP2Me1nZ-bSqSi3QCr1enA",
            "Photo": "https://drive.google.com/open?id=1MdyOJUaj_VY3SDVKBUmQfOTocYmt2_EL",
            "Email_Id": "nagdachaitri@gmail.com"
          },
          {
            "Id": 27,
            "Player_Name": "Sancheti Chintan Gosar",
            "Mobile_Number": 9870302259,
            "Location": "Vikhroli",
            "Village": "Manjal (Reladiya)",
            "NPL1_NPL2": "None",
            "Cricket_Type": "Bowling",
            "TShirt_Size": "M",
            "Age": 27,
            "Gender": "Niyani",
            "Payment_SS": "https://drive.google.com/open?id=1l2xq7AJjTkb9iXdO-f1NfeFlpa54rixG",
            "Photo": "https://drive.google.com/open?id=11Fx0evwsnExT8-L9iit7s5zKtdTe2rze",
            "Email_Id": "Sanchetinagda07@gmail.com"
          },
          {
            "Id": 28,
            "Player_Name": "Anjana Shantilal Gosar",
            "Mobile_Number": 9702342888,
            "Location": "Dombivli",
            "Village": "Reladiya Manjal",
            "NPL1_NPL2": "None",
            "Cricket_Type": "Allrounder",
            "TShirt_Size": "XXL",
            "Age": 49,
            "Gender": "Niyani",
            "Payment_SS": "https://drive.google.com/open?id=1Q08ARqiefUjzkKa9OXs9yzKW-Xz7eYxk",
            "Photo": "https://drive.google.com/open?id=1sF2KOTdbXHtW82E04Q_utGpSs09Tv7zt",
            "Email_Id": "gosardsg@yahoo.com"
          },
          {
            "Id": 29,
            "Player_Name": "Kusum Bipin Nagda",
            "Mobile_Number": 8766865687,
            "Location": "Nallasopara",
            "Village": "Godhra",
            "NPL1_NPL2": "None",
            "Cricket_Type": "Batting",
            "TShirt_Size": "M",
            "Age": 70,
            "Gender": "Female",
            "Payment_SS": "https://drive.google.com/open?id=1w0o4R3oxHwMkLp1mnOFfheyMy7LFuy1h",
            "Photo": "https://drive.google.com/open?id=1rE5uKX5zGCi4wZ-bxbrfzLGILFAW_dUi",
            "Email_Id": "Baf.hbn@gmail.com"
          },
          {
            "Id": 30,
            "Player_Name": "Krushi Ajay Nagda",
            "Mobile_Number": 8291618398,
            "Location": "Dombivli",
            "Village": "Sanosara",
            "NPL1_NPL2": "NPL-2",
            "Cricket_Type": "Bowling",
            "TShirt_Size": "L",
            "Age": 21,
            "Gender": "Female",
            "Payment_SS": "https://drive.google.com/open?id=1YjhzLBBhusqNTSrfT6D9SwXnu3lS8ldo",
            "Photo": "https://drive.google.com/open?id=1KV0LSw0eSzV_V9VjD5V7TmRjSwXNFE_c",
            "Email_Id": "Krushiajaynagda@gmail.com"
          },
          {
            "Id": 31,
            "Player_Name": "Suchi Kunjesh Nagda",
            "Mobile_Number": 8082052764,
            "Location": "Mulund",
            "Village": "Sanosara",
            "NPL1_NPL2": "None",
            "Cricket_Type": "Bowling",
            "TShirt_Size": "XXL",
            "Age": 31,
            "Gender": "Female",
            "Payment_SS": "https://drive.google.com/open?id=1P8Cffvp7w5fbpszj60YkUgLBaJySIGqD",
            "Photo": "https://drive.google.com/open?id=1xfCTuw2OU17ikT3icuAw-W7VktWQ6sFm",
            "Email_Id": "suchinagda@gmail.com"
          },
          {
            "Id": 32,
            "Player_Name": "Manali Satish Nagda",
            "Mobile_Number": 9158095380,
            "Location": "Vasai",
            "Village": "Bhojay",
            "NPL1_NPL2": "None",
            "Cricket_Type": "Allrounder",
            "TShirt_Size": "M",
            "Age": 26,
            "Gender": "Female",
            "Payment_SS": "https://drive.google.com/open?id=1Yd335HcNHFSamD9hIPqjLg2Mw17pMX5o",
            "Photo": "https://drive.google.com/open?id=1fleszlmK_fJMWJiX5KH_k2Dqpp80Yzvr",
            "Email_Id": "nagda.manali@gmail.com"
          },
          {
            "Id": 33,
            "Player_Name": "Krisha Bhavesh Nagda",
            "Mobile_Number": 9820799098,
            "Location": "Mulund",
            "Village": "Sonosara",
            "NPL1_NPL2": "None",
            "Cricket_Type": "Allrounder",
            "TShirt_Size": "S",
            "Age": 22,
            "Gender": "Female",
            "Payment_SS": "https://drive.google.com/open?id=1F0ZQyybYU0nh__H2KF19XR8j-dsytx8g",
            "Photo": "https://drive.google.com/open?id=1OE6Q8uMzA8I4nhKtD5056Vu0unkQP1W0",
            "Email_Id": "krishanagda01@gmail.com"
          },
          {
            "Id": 34,
            "Player_Name": "Deepa Vikram Nagda",
            "Mobile_Number": 9619611996,
            "Location": "Chembur",
            "Village": "Naredi",
            "NPL1_NPL2": "None",
            "Cricket_Type": "Allrounder",
            "TShirt_Size": "XXXL",
            "Age": 40,
            "Gender": "Female",
            "Payment_SS": "https://drive.google.com/open?id=1hrDeQWltuM4zGzC9ZrOGkBeWTXjYmy9S",
            "Photo": "https://drive.google.com/open?id=1ek4FYue8oE2KBb0LEKEBwHl8_Y04hMR9",
            "Email_Id": "tusmitshah@gmail.com"
          },
          {
            "Id": 35,
            "Player_Name": "Sneha Shah",
            "Mobile_Number": "07738301381",
            "Location": "Mulund",
            "Village": "Bhojay",
            "NPL1_NPL2": "None",
            "Cricket_Type": "Batting",
            "TShirt_Size": "3XL",
            "Age": 34,
            "Gender": "Female",
            "Payment_SS": "https://drive.google.com/open?id=1Vu3ZrItPtFHEbT-z6cE4kjjt4iXs41Vh",
            "Photo": "https://drive.google.com/open?id=1U7ZjBaZIQAYbyD-tij3KkKGQyB7Cr6cB",
            "Email_Id": "nagda.sneha@gmail.com"
          },
          {
            "Id": 36,
            "Player_Name": "Sejal Khushal Nagda",
            "Mobile_Number": 9821010109,
            "Location": "Dombivli",
            "Village": "Bhojay",
            "NPL1_NPL2": "Both",
            "Cricket_Type": "Batting",
            "TShirt_Size": "S",
            "Age": 21,
            "Gender": "Female",
            "Payment_SS": "https://drive.google.com/open?id=1a1L7I7SkoQby_nCJ0nXFyBUD2MLbmQjY",
            "Photo": "https://drive.google.com/open?id=1qbrvIQ3sG6VlcIZVlBVMC2l3wDipttGO",
            "Email_Id": "Sejalnagda100@gmail.com"
          },
          {
            "Id": 37,
            "Player_Name": "Vimi Shah",
            "Mobile_Number": 9819885119,
            "Location": "Mulund",
            "Village": "Vidh",
            "NPL1_NPL2": "Both",
            "Cricket_Type": "Allrounder",
            "TShirt_Size": "M",
            "Age": 34,
            "Gender": "Female",
            "Payment_SS": "Vijay Paid",
            "Photo": "https://drive.google.com/open?id=1qNDyEDvcqUCvNTfgnk8CVZre4Mjwh0Se",
            "Email_Id": ""
          },
          {
            "Id": 38,
            "Player_Name": "Laxmi Arvind vira",
            "Mobile_Number": 9821961335,
            "Location": "",
            "Village": "Makda",
            "NPL1_NPL2": "Both",
            "Cricket_Type": "Allrounder",
            "TShirt_Size": "L",
            "Age": 52,
            "Gender": "Female",
            "Payment_SS": "Cash Denge",
            "Photo": "https://drive.google.com/open?id=13m_8AXwjOVwM4c42TEvzl4bR41EIabLH",
            "Email_Id": ""
          }
        ];
       }
        
    }


    
